---
title: 'NO$_2$ Sensor Analysis'
author: "Coleman Breen"
date: "September 10, 2018"
output: 
  html_document:
    keep_md: true
---
## Analysis and visualization of NO$_2$ in the US

Today we'll be looking at the presence of NO$_2$ around the UNited States. NO$_2$ is emitted by cars burning fossil fuels. Excess Nitrogen Dioxide causes respiratory issues in humans. It also causes acid rain and can create enough air pollution to make it hard to see. The National Ambient Air Quality Standards say that 100 parts per billion (ppb) is a safe exposure for one hour at a time. This gives us some idea about how much NO$_2$ is too much. You can read more about it [here](https://www.epa.gov/no2-pollution).  
  
We can look at data on NO$_2$ from the [EPA's website.](https://aqs.epa.gov/aqsweb/airdata/download_files.html)  In particular, we are interested in daily NO$_2$ levels for 2017. Later in this analysis, we'll also pull in O$_3$ data and compare the two pollutants.


```r
#--> Setup environment
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
```

```
## -- Attaching packages ----------------------------------------------------------------------------------------------------- tidyverse 1.2.1 --
```

```
## v ggplot2 3.0.0     v purrr   0.2.5
## v tibble  1.4.2     v dplyr   0.7.6
## v tidyr   0.8.1     v stringr 1.3.1
## v readr   1.1.1     v forcats 0.3.0
```

```
## -- Conflicts -------------------------------------------------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
```


```r
#--> Load in data
no2_df <- read_csv('data/daily_42602_2017.csv')
names(no2_df)
```

```
##  [1] "State Code"          "County Code"         "Site Num"           
##  [4] "Parameter Code"      "POC"                 "Latitude"           
##  [7] "Longitude"           "Datum"               "Parameter Name"     
## [10] "Sample Duration"     "Pollutant Standard"  "Date Local"         
## [13] "Units of Measure"    "Event Type"          "Observation Count"  
## [16] "Observation Percent" "Arithmetic Mean"     "1st Max Value"      
## [19] "1st Max Hour"        "AQI"                 "Method Code"        
## [22] "Method Name"         "Local Site Name"     "Address"            
## [25] "State Name"          "County Name"         "City Name"          
## [28] "CBSA Name"           "Date of Last Change"
```

```r
#--> Order the variables
no2_df <- select(no2_df, 'State Name', 'City Name', 'AQI', 'Arithmetic Mean', 'Observation Percent', 
                 'Observation Count', 'Date Local', 'Latitude', 'Longitude', everything())
names(no2_df)
```

```
##  [1] "State Name"          "City Name"           "AQI"                
##  [4] "Arithmetic Mean"     "Observation Percent" "Observation Count"  
##  [7] "Date Local"          "Latitude"            "Longitude"          
## [10] "State Code"          "County Code"         "Site Num"           
## [13] "Parameter Code"      "POC"                 "Datum"              
## [16] "Parameter Name"      "Sample Duration"     "Pollutant Standard" 
## [19] "Units of Measure"    "Event Type"          "1st Max Value"      
## [22] "1st Max Hour"        "Method Code"         "Method Name"        
## [25] "Local Site Name"     "Address"             "County Name"        
## [28] "CBSA Name"           "Date of Last Change"
```
You can read about what's in the dataset [here.](https://aqs.epa.gov/aqsweb/airdata/FileFormats.html) A few takeaways:  

1. State Code-County Code-Site Num-Parameter Code gives a unique identifier for each individual sensor. There can be multiple sensors with the same State Code-County Code-Site Num.  
2. Sample Duration deals with the "length of time that air passes through the monitoring device."  
3. Event Type can include things like wildfires and other things we may/may not want to include in analysis.  
4. Arithmetic mean is the average presence of NO$_2$ (in ppb).  
5. 1st Max Value gives the highest value of the day.

# How many sensors are measuring NO$_2$?  
To answer this question we will have to find how many unique sensore there are. This data set reports information from many sensors and different times of the day.


```r
#--> Create a unique identifier based on state, county codes, and site number
no2_df %>%
  mutate(Identifier = paste(no2_df$'State Code', no2_df$'County Code', 
                            no2_df$'Site Num', sep = '-')) -> no2_df

#--> Number of unique sensors
length(unique(no2_df$Identifier))
```

```
## [1] 451
```
There are 451 sensors around the United States measuring NO$_2$.

# How well do these sensors work?  

We will do some more manipulation to create a variable telling us what percent of the year each distinct sensor is working. The data report observation percent for individual days. We'll group these observations by the unique identifier we created earlier and then average their daily working percentage.


```r
#--> Yearly percent that unique sensors are working
no2_df %>%
  group_by(Identifier) %>%
  summarise_at(vars('Observation Percent'), mean) %>%
  ungroup() -> no2_simple_df

#--> Join the unique sensors, yearly percentage, and lat/long
no2_df %>%
  ungroup() %>%
  select('Identifier', 'Latitude', 'Longitude') %>%
  full_join(no2_simple_df, by = 'Identifier') %>%
  distinct() -> no2_simple_df

#--> Rename variable 
no2_simple_df <- rename(no2_simple_df, 'YearlyObsPercent' = 'Observation Percent')
head(no2_simple_df)
```

```
## # A tibble: 6 x 4
##   Identifier  Latitude Longitude YearlyObsPercent
##   <chr>          <dbl>     <dbl>            <dbl>
## 1 01-073-0023     33.6     -86.8             90.7
## 2 01-073-2059     33.5     -86.8             89.2
## 3 02-090-0034     64.8    -148.              95.3
## 4 04-013-0019     33.5    -112.              98.5
## 5 04-013-3002     33.5    -112.              98.7
## 6 04-013-4011     33.4    -113.              98.4
```
We'll plot the distribution of 'YearlyObsPercent' to see how the sensors fare.


```r
library(ggplot2)

#--> Simple histogram of sensor working percent
ggplot(no2_simple_df, aes(YearlyObsPercent)) +
  geom_histogram(binwidth = .5, fill = 'forestgreen', alpha = .75) +
  theme_light() +
  xlab('Time Working (percent of year)') +
  ylab('Frequency')
```

![](nitrous_dioxide_in_us_analysis_files/figure-html/unnamed-chunk-6-1.png)<!-- -->

```r
#--> Summary statisitcs for good measure
summary(no2_simple_df$YearlyObsPercent)
```

```
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   84.28   94.53   96.26   95.89   97.67   99.67
```

Sensors seem to be very reliable. Nearly 3 in 4 sensors worked at least 95% of the year 2017. Most work well over 90% of the time.

# Mapping the sensor locations


```r
library(ggmap)

#--> Bound the map's coordinates
no2_simple_df %>%
  make_bbox(lat = Latitude, lon = Longitude) -> sensor_bbox

#--> Create and print map
sensor_map <- get_map(location = sensor_bbox, maptype = "toner-lite", zoom = 3)

#--> Overlay sensors
ggmap(sensor_map) +
  geom_point(data = no2_simple_df, mapping = aes(x = Longitude, y = Latitude), color = 'blue', alpha = .25)
```

![](nitrous_dioxide_in_us_analysis_files/figure-html/unnamed-chunk-7-1.png)<!-- -->

This gives us some sense of where the sensors are located to begin with. We see a higher concentration around California, Eastern Texas, and New England. There seems to be quite a few in Northern Utah and Wyoming, considering that those areas are not as densley populated.

# Mapping NO$_2$ 

We'll now turn our attention towards the presences of Nitrous Dioxide itself. Where is it most densley concentrated? 

We don't have sensor data for each county so we will construct a heat map of the presence of NO$_02$ around the US.


```r
#--> Rename variables so that DPLYR doesn't get tripped up by the spaces
no2_df <- rename(no2_df, 'DailyMeanPPB' = 'Arithmetic Mean')

#--> Compute a yearly average of NO2
no2_df %>%
  group_by(Identifier) %>%
  summarise_at(vars('DailyMeanPPB'), mean) %>%
  ungroup() -> daily_mean_no2_df

#--> Compute a yearly mean AQI
no2_df %>%
  group_by(Identifier) %>%
  summarise_at(vars('AQI'), mean) %>%
  ungroup() -> daily_mean_AQI_df

#--> Join the unique sensors, yearly NO2 ppb, and coordinates
no2_df %>%
  ungroup() %>%
  select('State Name', 'City Name', 'Identifier', 'Latitude', 'Longitude') %>%
  full_join(daily_mean_no2_df, by = 'Identifier') %>%
  distinct() %>%
  full_join(daily_mean_AQI_df) %>%
  distinct() %>%
  rename('DailyMeanAQI' = 'AQI') -> daily_mean_no2_df

rm(daily_mean_AQI_df)

#--> Take a look 
head(daily_mean_no2_df, 5)
```

```
## # A tibble: 5 x 7
##   `State Name` `City Name` Identifier Latitude Longitude DailyMeanPPB
##   <chr>        <chr>       <chr>         <dbl>     <dbl>        <dbl>
## 1 Alabama      Birmingham  01-073-00~     33.6     -86.8         9.07
## 2 Alabama      Birmingham  01-073-20~     33.5     -86.8        11.5 
## 3 Alaska       Fairbanks   02-090-00~     64.8    -148.         12.5 
## 4 Arizona      Phoenix     04-013-00~     33.5    -112.         17.0 
## 5 Arizona      Phoenix     04-013-30~     33.5    -112.         18.3 
## # ... with 1 more variable: DailyMeanAQI <dbl>
```

We've created a data frame that gives us the average daily ppb of NO$_2$ linked to specific coordinates on a map. We'll create a heat map to visualize the presence of Nitrous Dioxide around the lower 48.


```r
#--> Take out Alaska, Hawaii, Puerto Rico to see trends in the lower 48
remove_states_v = c("Alaska", "Hawaii", "Puerto Rico")

daily_mean_no2_df %>%
  filter(!('State Name' %in% remove_states_v)) %>%
  filter(Longitude > -142) -> daily_mean_no2_df
```


```r
#--> Bound the map's coordinates
daily_mean_no2_df %>%
  make_bbox(lat = Latitude, lon = Longitude) -> no2_box

#--> Create underlying map
no2_map <- get_map(location = no2_box, maptype = "toner-lite", zoom = 3)

#--> Need RColorBrewer
library(RColorBrewer)

#--> Overlay heat map info (NO2)
ggmap(no2_map) +
  stat_density2d(data = daily_mean_no2_df, 
             mapping = aes(x = Longitude, y = Latitude, fill =..level..), 
             geom = "polygon", alpha = .3) +
  scale_fill_gradientn(name = "NO2 (%)", colours=rev(brewer.pal(10, "Spectral"))) 
```

![](nitrous_dioxide_in_us_analysis_files/figure-html/unnamed-chunk-10-1.png)<!-- -->

We can see greater concentrations of NO$_2$ around Southern California, Northern Utah/Colorado, East Texas/Louisiana, and New England. However, stat_density_2d is not as precise because we are seeing NO$_2$ measurements where there are no sensors. Let's try this using sf.


```r
#--> Load in libraries
library(sf)
library(leaflet)

#--> Create an sf compatable data type
daily_mean_no2_df <- daily_mean_no2_df[order(daily_mean_no2_df$DailyMeanPPB), ]
daily_mean_no2_sf <- st_as_sf(daily_mean_no2_df, coords = c("Longitude", "Latitude"))

#--> Color spectrum
Npal <- colorNumeric(
  palette = "YlOrRd", n = 10,
  domain = daily_mean_no2_sf$DailyMeanPPB
)

#--> Make our map
no2_circles_map <- daily_mean_no2_sf %>%
  leaflet() %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
  addCircles(radius = daily_mean_no2_sf$DailyMeanPPB*5000, fillOpacity = .6, 
             fillColor = Npal(daily_mean_no2_sf$DailyMeanPPB), stroke = FALSE) %>%
  addLegend("bottomright", pal = Npal, values = ~DailyMeanPPB, 
            labFormat = function(type, cuts, p) {
              n = length(cuts) 
              paste0(prettyNum(cuts[-n], digits=0, big.mark = ",", scientific=F), 
                     " - ", prettyNum(cuts[-1], digits=0, big.mark=",", scientific=F))},
            title = "Avg. Daily NO2 (ppb)", opacity = 1)

no2_circles_map
```

<!--html_preserve--><div id="htmlwidget-39301339e8bde3942cb2" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-39301339e8bde3942cb2">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["Stamen.TonerLines",null,"Basemap",{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addProviderTiles","args":["Stamen.TonerLite",null,"Basemap",{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[34.48974,40.71528,42.529999,34.596095,43.081667,43.101281,40.038889,44.138619,35.63348,47.048537,34.725538,34.54166,43.74561,42.7907,48.317507,36.035,37.30389,45.440295,47.803392,39.92002,39.240278,47.8679,41.386944,34.402773,35.4325,42.373499,42.486361,44.6522,40.086944,41.615237,44.310555,47.5812,41.750556,32.941023,27.350278,32.344008,42.751518,39.70595,47.940861,41.373097,39.474976,41.644722,32.668987,48.64193,34.44551,40.695078,44.980577,47.400624,35.03146,42.298493,30.700895,34.52744,32.175417,29.043759,44.657014,40.206291,44.146964,47.3132,32.031934,38.683304,47.185833,29.254474,31.653074,30.315406,40.268963,42.814412,37.179125,42.862531,29.863957,40.776944,47.298611,39.60996,37.689615,38.770081,37.67696,40.787628,32.564968,45.366151,33.944713,39.021881,42.869824,40.05671,29.978926,30.350302,37.205862,43.42542,30.039524,34.46245,32.380118,35.763873,37.47689,42.14175,44.230622,40.600532,25.732878,44.77553,41.677667,32.378682,38.302591,30.085263,34.63782,33.153088,37.103733,41.705226,40.811389,33.447867,41.182227,42.211774,27.892523,29.583047,37.34438,38.71209,40.46471,32.842242,34.131262,26.593808,29.670025,30.378287,29.275381,40.294178,28.596389,39.43806,32.726656,35.49453,38.85287,42.82231,37.780776,38.45934,46.933754,42.8608,47.241153,42.474642,34.877064,36.69676,38.53445,43.54792,30.221255,44.097074,31.787885,32.482083,36.796667,37.05822,30.354436,27.785866,37.13678,38.06503,38.403765,32.98426,33.219069,48.459928,37.682512,38.006311,32.676451,29.520443,40.483598,37.28342,42.8463,40.146667,46.825425,34.252378,42.19438,35.479215,35.40814,42.719,26.088421,35.856111,37.743649,35.346094,36.809735,41.842649,37.10258,38.650783,38.613779,32.919206,30.036422,40.309722,39.422273,30.262604,41.79358,41.530011,40.617488,30.041238,44.4762,31.796218,33.217025,30.229653,44.80353,39.02473,34.949147,44.087397,32.79222,45.13768,29.51509,39.761538,34.427775,32.656357,40.496392,29.695729,41.603159,36.867125,42.738618,40.216779,43.608056,33.85275,41.841039,39.055277,35.477036,37.936013,41.30283,36.204902,30.356339,39.9679,35.2401,32.882289,36.110693,37.702066,40.628056,35.197288,37.281598,36.59745,39.138773,36.841331,36.8071,38.310942,39.12886,36.85555,29.901036,34.756189,43.660246,44.76323,41.69666,37.55652,34.671394,34.843895,33.37005,34.276362,32.820061,33.67464,25.798709,32.805818,38.47753,38.745726,36.205055,32.579361,40.462182,33.92086,39.965278,39.96523,38.102507,36.270592,37.9604,38.013333,29.5294,33.67649,40.747796,32.29515,44.706123,27.834409,32.204411,36.314399,41.118333,38.612034,45.496641,37.687526,33.6878,41.13069,41.825556,41.442778,41.784722,38.22876,35.503587,41.4408,43.060975,32.92118,33.553056,43.145013,32.845467,32.631231,39.117219,18.198712,39.988842,33.9508,29.802707,35.8652,30.500642,42.43084,42.421502,38.673221,38.8577,42.921107,29.686389,37.97231,39.835556,42.876907,41.606667,38.558228,39.810833,37.487981,39.310833,27.955133,34.14435,29.733726,18.422595,29.996013,40.92458,34.05111,32.789561,38.970092,30.461981,38.75264,35.16126,40.43743,36.819111,31.768291,35.1343,36.742227,37.743065,29.834167,34.38344,38.921847,30.262778,39.739444,37.482934,35.213171,36.332179,38.63114,42.386811,40.11107,38.895572,40.054171,36.785322,38.656429,42.3295,39.047911,41.492117,37.765946,32.664722,42.263955,37.950741,33.521427,29.767997,42.290767,47.568236,40.902967,25.785472,39.934446,39.104686,36.705506,42.108992,37.348497,32.676186,45.393497,37.59088,29.7216,38.593322,31.746775,35.331302,39.525083,34.510014,40.736389,35.356601,34.19925,41.7514,39.787933,41.3014,30.35386,33.995638,42.348873,31.765685,37.814781,44.965242,42.932658,42.325186,39.297733,42.280097,33.83062,29.758889,36.1424,29.81453,39.371679,33.92513,39.838119,38.1936,34.895007,40.253611,26.132677,28.53493,33.698643,40.8679,40.67025,33.99958,38.76835,38.89477,40.720989,33.503833,40.73614,34.1326,34.10374,36.141875,41.855243,41.877682,34.1365,41.965193,42.385998,39.14313,34.10688,35.50307,33.901389,37.864767,41.771444,32.985442,40.739264,37.793624,36.191251,43.593929,33.48385,37.338135,40.816,47.22634,40.853579,33.7784,33.8025,36.163962,41.829495,41.206321,33.45793,39.77949,34.10002,39.751184,40.64144,40.008889,34.01194,39.146025,40.731645,47.597222,34.06659,36.710833,34.06703,33.39625,33.819305,36.174365,39.73217,33.859444,36.139707,39.7861,34.067802,33.461554,34.030833],[-120.04692,-124.20139,-108.720003,-120.631282,-107.549444,-105.498931,-107.8475,-87.6161,-83.941606,-109.455315,-120.428774,-119.79146,-101.941218,-110.0551,-107.862471,-107.904167,-107.484167,-105.370283,-104.485552,-77.30968,-105.983056,-104.676944,-107.616667,-119.458454,-79.2887,-109.560498,-110.098861,-105.2903,-108.761389,-71.72,-84.891865,-103.2995,-109.788333,-79.657187,-82.479722,-95.415752,-96.707208,-79.012,-101.571583,-111.042376,-91.788991,-76.939167,-94.167457,-102.4018,-119.8284,-92.006318,-74.695005,-101.929099,-120.50103,-72.334079,-91.056068,-120.1965,-96.870189,-95.472946,-111.089618,-109.353932,-105.529994,-102.5273,-96.399141,-121.164457,-101.428056,-94.861289,-97.070698,-90.811383,-80.243995,-70.817783,-113.305096,-71.38014,-94.317802,-124.1775,-101.766944,-110.800749,-121.631916,-99.763424,-95.47594,-74.676301,-96.317687,-106.48982,-116.830074,-84.47445,-109.87076,-109.688108,-94.010872,-95.425128,-107.254118,-105.388566,-95.673951,-120.02551,-104.262726,-117.397004,-97.366399,-80.038611,-69.785,-112.353414,-80.16175,-93.06299,-108.024835,-94.711811,-121.420838,-93.761341,-120.4575,-96.115572,-76.387017,-76.512726,-77.877028,-117.088649,-104.778334,-71.11397,-82.538429,-95.015544,-77.25925,-121.38109,-109.561472,-116.768225,-80.868318,-80.058492,-95.128508,-88.53393,-98.311692,-110.009732,-81.3625,-108.02611,-103.122917,-120.66617,-77.63462,-106.36501,-87.075307,-82.64041,-96.85535,-106.23586,-119.847824,-70.970816,-97.707801,-121.637182,-121.7734,-96.700769,-91.315418,-105.343164,-106.683324,-97.026899,-108.473138,-88.57251,-97.760255,-82.739875,-107.62863,-84.49761,-122.818294,-97.063721,-97.196284,-122.520388,-121.443324,-121.641918,-96.87206,-95.392509,-109.906796,-79.88452,-106.27767,-79.902222,-100.76821,-119.143176,-72.555112,-97.751503,-94.524413,-109.753,-80.111193,-78.574167,-121.934188,-118.852037,-107.652192,-111.852199,-107.870219,-121.506767,-121.368014,-96.808498,-94.071061,-78.915,-75.025204,-93.285084,-107.08422,-90.587611,-79.727664,-90.272826,-73.2106,-106.584434,-117.396158,-90.965628,-106.961763,-77.48925,-120.43763,-103.273777,-115.56306,-93.207615,-98.620166,-121.84162,-119.691218,-97.088585,-112.036298,-95.499219,-93.643118,-120.010158,-84.534633,-110.182742,-72.982778,-116.54101,-71.36097,-76.878333,-97.494309,-122.026154,-105.586,-95.976537,-81.635396,-80.7464,-80.785683,-79.977538,-80.226438,-97.314847,-75.341111,-90.193141,-120.434992,-119.504569,-121.618549,-119.875415,-108.69523,-122.296189,-84.50404,-76.30135,-95.326137,-92.281296,-70.268965,-93.03255,-86.214722,-77.40027,-118.131456,-82.414585,-112.6207,-118.683757,-96.860117,-117.92568,-80.210048,-97.356568,-78.81952,-121.266312,-86.74472,-116.929486,-74.429439,-116.85841,-76.699444,-82.95549,-122.237976,-115.238282,-122.356811,-87.577222,-98.39139,-117.33098,-80.316442,-110.9823,-93.285803,-82.665251,-110.878067,-119.64457,-73.336667,-90.160477,-122.602877,-121.784217,-84.2905,-104.75308,-71.405278,-75.623056,-72.631667,-85.65452,-119.272606,-81.4948,-87.913504,-96.75355,-86.815,-77.55728,-117.123894,-117.059075,-94.635605,-66.052237,-75.207205,-118.43043,-95.125495,-78.8197,-91.213556,-83.000138,-83.425042,-90.239166,-77.05922,-78.765825,-95.294722,-122.520004,-75.3725,-78.809526,-87.304722,-121.492981,-86.114444,-120.837005,-76.474444,-82.469532,-117.85036,-95.257593,-66.120012,-90.11819,-75.067815,-118.45636,-116.944222,-77.016715,-91.179219,-90.44884,-89.87065,-79.863572,-119.717356,-106.50126,-106.5852,-107.977567,-122.169935,-95.489167,-118.5284,-77.013178,-81.606833,-75.558056,-122.20337,-80.874084,-119.291228,-90.28115,-83.270506,-83.065415,-76.958072,-74.985166,-119.774174,-90.198348,-71.0826,-94.450513,-81.678449,-122.399044,-97.338056,-71.794322,-121.268523,-86.844112,-95.220582,-83.12066,-122.308628,-111.884467,-80.284206,-75.125291,-94.57079,-119.741966,-72.590803,-121.894898,-115.484144,-122.747894,-77.46925,-95.49265,-121.503795,-106.402806,-119.000974,-119.807717,-117.331433,-111.872222,-119.063542,-118.53276,-87.713488,-86.13088,-72.902871,-97.69166,-117.493304,-71.097163,-106.455227,-122.282347,-93.254759,-87.9344,-71.056061,-76.604603,-83.120122,-117.93845,-95.079444,-86.7341,-95.38769,-76.746814,-117.95264,-104.94984,-85.7119,-117.024484,-111.663056,-80.169817,-81.384247,-84.272614,-73.87809,-74.126081,-117.41601,-77.18347,-76.953426,-74.192892,-112.095767,-73.82153,-118.1272,-117.62914,-115.078742,-87.75247,-87.635027,-117.92391,-87.876265,-83.266189,-76.84611,-117.27411,-97.577981,-118.205,-122.302741,-72.679923,-117.08218,-73.817694,-122.263376,-115.122953,-116.38125,-112.14257,-121.849783,-73.902,-122.46256,-73.966212,-84.3914,-118.22,-115.11393,-71.417457,-111.975524,-112.04601,-105.00518,-117.49201,-104.987625,-74.208365,-75.09778,-118.06995,-84.538375,-74.066308,-122.319722,-118.22688,-119.7775,-117.7514,-111.967972,-117.918759,-115.13977,-105.0153,-118.200278,-115.175654,-104.9886,-117.526711,-112.128159,-117.61722],[-1193.77584302326,178.884901129943,1460.70656976744,1773.61783430233,2030.38398529412,2110.98750684932,2379.85031531532,2440.05285,2766.50785911602,2775.14710059172,2822.14884401114,3097.77585635359,3183.78834261838,3193.66177197802,3502.79904530744,3763.6878852459,4073.29276712329,4206.72491304348,4255.99964912281,4283.74922155689,4288.12134615385,4513.37345771144,5337.63992795389,5933.18581602374,5956.43845730028,6442.53364640884,6539.18120547945,6703.50908219178,6773.70930232558,6775.38262254902,7095.49002747253,7163.77701369863,7261.94504109589,7400.02805084746,7779.7181085044,7923.5743543956,8247.56790055249,8670.40739669421,9144.94585889571,9281.68065753425,9347.0526617647,9498.80008426966,9558.51127094972,9994.69636986301,10149.9886029412,10567.1573835616,10603.1333529412,10640.4732191781,10820.9008219178,10876.669875,11074.4423561644,11080.6338630137,11121.1607002801,11256.6408166189,11475.5644366197,11645.7811344538,11720.3209166667,11787.4631291391,11907.3649159664,12028.0566475645,12029.4584285714,12317.9874929972,12361.91203125,12505.0333238636,12531.3361290323,12735.4313711911,12763.4997005988,13141.8742039106,13167.1291,13187.4459636872,13333.9308425414,13481.437466443,13853.5147159091,14194.0122054795,14401.0346849315,14431.5740384615,14443.9002209945,14556.8275479452,14587.4953287671,14671.9611242604,14688.6725068493,14790.3670547945,14854.6796478873,15123.5470410959,15243.9953301887,15268.1933835616,15499.0101260504,15530.0006438356,16157.2481039326,16159.6260557185,16211.9584602649,16244.1724029851,16268.4484297521,16536.2579714286,16683.3594833333,16882.3567945205,16885.7725342466,17007.0625479452,17332.6959285714,17421.5379551821,17552.3623561644,17626.8448493151,17816.010890411,18017.3239859155,18035.0815472779,18159.9883086053,18224.1712073864,18580.2969889503,18870.9186728395,18972.2926330532,19091.506800554,19674.2615,19714.232347561,19747.6034383562,19845.0823342939,20016.7617105263,20102.4625095057,20200.7914779006,20213.2827668539,20292.9785302594,20537.6039088398,20566.1077259887,20847.732630137,20879.966717033,21010.6384520548,21200.6734246575,21345.7333482143,21348.9118543956,21709.9221780822,21906.931446281,22022.1844074074,22088.5522054794,22141.8443298969,22176.5055890411,22191.5167731629,22353.6685890411,22405.4484305556,22495.7302328767,22496.7558149171,22564.9741506849,22621.3737313433,22962.8945601173,22971.4784657534,23144.77,23355.0482465753,23895.2339969136,23905.9418082192,23939.7180939227,23946.2261357341,24208.6563905325,25063.9207977208,25722.2589178082,25942.3870054945,25947.3287430168,26130.5621506849,26193.9230136986,26275.9047671233,26513.297917847,26655.0736126374,26726.6700958904,26746.7777961433,26748.8915277778,26799.4721965318,27180.7406164384,27223.8725352113,27305.6293939394,27307.05875,27523.1246969697,27537.613343949,27568.2104936306,28456.2832028986,28495.8944039735,28509.9492982456,28721.3468818681,28772.9266949153,28792.9,28858.0949863014,29020.6711604585,29060.4516849315,29413.0483379501,29639.8663920455,30077.8412739726,30145.7989315068,30606.4659589041,30698.6816620499,30703.3194985673,30728.7555932203,30926.1872328767,30990.349375,30994.5647329377,31212.9985849057,31345.5819863014,31426.1158171745,31496.9244794521,31519.4732352941,31632.5685650888,31657.0658507463,32037.8730477528,32130.6324931507,32244.3702465753,32371.1073573574,32429.2130440771,32547.6249171271,32733.9528729282,32753.6166849315,32868.9949585635,33266.093375,33346.2766946779,33443.1122633745,34568.4257554945,34696.2262606232,34707.1837671233,34970.5306901408,35079.7969488189,35179.2844520548,35342.2785179153,35348.4536280488,35407.7009203297,35684.3242032967,35895.3416620879,36008.0270441989,36084.9860547945,36923.3490974212,36937.9699863014,37209.6977018634,37289.6275931232,37406.3944247788,37929.435109589,38143.0961369863,38267.249260274,38279.455652819,38478.7146254072,38481.7114183381,38503.1312739726,38650.4956736527,38749.907109589,39058.0753846154,39249.3809392265,39461.1329761905,39525.5661506849,39530.6863835616,39562.3174383562,39563.563260274,39835.5356164384,39840.9999726027,39956.7534122563,40560.319640884,40563.8360330579,40570.275989011,40601.866771978,40688.3787671233,40780.1544590643,41032.8362063953,41339.9346027397,41586.816978022,41589.2980958904,41840.9314931507,42121.2693818681,42192.1658767123,42283.2802328767,42787.8021895425,43154.1617613636,43177.4125698324,43181.2256027397,43331.9025925926,43746.7757978723,43813.7769589041,44329.547239011,44371.2577700831,44419.7562724014,44479.8470784884,44800.1436149584,44906.7328055556,45261.9037671233,45338.5491436464,45548.7637047354,45890.2874309392,46020.8106705539,46135.9889971347,46258.5144848485,46454.9436543909,46474.9003240741,46476.1034733894,46698.0538872832,46708.7842074928,46729.9398189415,46871.4448493151,47364.4667897727,47461.728369863,47561.8124587912,47833.6719241573,48027.5088493151,48042.6873051948,48124.8709863014,48203.7534180791,48524.2885082873,48739.1070845481,48856.3490536723,49636.9098194444,49753.4527591463,49927.6632054795,49930.7448728814,50199.9859937888,50533.2164520548,50548.9992739726,50635.0305676856,50773.0087743733,50777.3863835616,50777.9178983516,50872.8452191781,50899.9564246575,51275.0288630137,51630.9597887324,51672.4488418079,51762.7038630137,52093.7304945055,52345.7312054795,52449.4336158192,52519.5586016949,52775.7706232687,53175.8480087209,53526.3198174157,53859.3547260274,53907.0738538682,54317.789505814,54619.5183185841,55465.8526470588,55482.0584657534,55909.4300273973,56085.0712534819,56183.4790807799,56356.8687260274,56645.4019971671,56740.9794931507,56847.8015068493,57191.7080136986,57252.283433908,57396.4665068493,57474.5915384615,57556.7355555556,57621.6022809668,57658.2859452055,57943.5141923077,58077.2052721088,58156.9363980263,58713.7109178082,58820.4804520548,59964.9100141643,60074.9649150142,61140.6057348703,62016.2129258242,62030.266109589,62087.0606410256,62095.5752028986,62614.0600815217,62929.5398214286,63427.7701805555,63486.4808495822,63529.1019452055,64024.618953125,64107.6916986301,64418.9835014837,64440.8858082192,64530.4775501433,64981.9595710059,65347.6411506849,66030.6775205479,66324.6522739726,66822.9882673267,66897.1535070423,67120.094739726,67618.4845694445,68821.4894383562,68874.2908286517,68978.7213559322,70540.9897592068,71628.1258041958,71770.8914520548,71801.0682285714,72377.096260274,72634.5337534247,72884.5887538941,72945.382109589,73005.5337945205,73047.5537267081,73817.2162786885,74567.7989869281,74580.1607671233,74625.6122191781,74757.265109589,74837.3535342466,74865.8168219178,74935.5354834254,75045.6041322314,75902.5107366771,76492.255630137,76521.0638781163,76640.9064109589,78071.4527969349,78230.9447916667,78808.0955205479,78991.7891917808,79099.6453038674,79317.4952924791,79620.0745389049,79685.2046986301,80104.9131921824,80652.3093835616,80701.5041346154,81417.1669178082,81575.0603714286,81815.0226727273,83907.9517945205,84603.5739178082,84994.8292783505,85007.9596575342,85009.7639041096,86623.6856465517,87255.2246142857,87806.9554494382,89071.4025482094,89638.0410335196,90088.578479452,90555.707739726,91196.0157142857,91284.3889452055,91972.6279863014,92170.2236666667,96279.1310547945,96854.6348082192,97781.0457222222,98268.9191736695,99649.8736986301,100363.468471074,102546.76710443,102666.459656593,103112.901112637,103156.788861111,108596.274493151,112814.858219178,119045.013890411,122190.652373595,126375.286304945,135533.327835616,136955.902311978,144118.427665746,153077.058671233,160391.87976257],null,null,{"interactive":true,"className":"","stroke":false,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":["#FFFFCC","#FFFEC9","#FFFDC6","#FFFCC6","#FFFCC5","#FFFCC5","#FFFCC4","#FFFCC4","#FFFBC3","#FFFBC3","#FFFBC3","#FFFBC3","#FFFBC2","#FFFBC2","#FFFBC2","#FFFBC1","#FFFAC1","#FFFAC0","#FFFAC0","#FFFAC0","#FFFAC0","#FFFAC0","#FFF9BE","#FFF9BC","#FFF9BC","#FFF8BB","#FFF8BB","#FFF8BB","#FFF8BB","#FFF8BB","#FFF8BA","#FFF8BA","#FFF7BA","#FFF7B9","#FFF7B8","#FFF7B8","#FFF7B7","#FFF6B7","#FFF6B5","#FFF6B5","#FFF6B5","#FFF5B5","#FFF5B5","#FFF5B4","#FFF5B3","#FFF4B2","#FFF4B2","#FFF4B2","#FFF4B2","#FFF4B2","#FFF4B1","#FFF4B1","#FFF4B1","#FFF4B1","#FFF4B0","#FFF4B0","#FFF3B0","#FFF3B0","#FFF3AF","#FFF3AF","#FFF3AF","#FFF3AF","#FFF3AE","#FFF3AE","#FFF3AE","#FFF3AE","#FFF3AE","#FFF2AD","#FFF2AD","#FFF2AD","#FFF2AC","#FFF2AC","#FFF2AB","#FFF1AA","#FFF1AA","#FFF1AA","#FFF1AA","#FFF1AA","#FFF1AA","#FFF1A9","#FFF1A9","#FFF1A9","#FFF1A9","#FFF0A8","#FFF0A8","#FFF0A8","#FFF0A8","#FFF0A8","#FFF0A6","#FFF0A6","#FFEFA6","#FFEFA6","#FFEFA6","#FFEFA5","#FFEFA5","#FFEFA5","#FFEFA5","#FFEFA4","#FFEEA4","#FFEEA3","#FFEEA3","#FFEEA3","#FFEEA3","#FFEEA2","#FFEEA2","#FFEEA2","#FFEEA2","#FFEDA1","#FFEDA0","#FFEDA0","#FFEDA0","#FFEC9F","#FFEC9F","#FFEC9E","#FFEC9E","#FFEC9E","#FFEC9E","#FFEC9E","#FFEC9E","#FFEC9D","#FFEB9D","#FFEB9D","#FFEB9C","#FFEB9C","#FFEB9C","#FFEB9B","#FFEB9B","#FFEB9B","#FFEA9A","#FFEA9A","#FFEA9A","#FFEA9A","#FFEA9A","#FFEA99","#FFEA99","#FFEA99","#FFEA99","#FFEA99","#FFEA99","#FFE999","#FFE999","#FFE998","#FFE998","#FFE997","#FFE997","#FFE896","#FFE896","#FFE896","#FFE896","#FFE895","#FFE793","#FFE692","#FFE692","#FFE692","#FFE691","#FFE691","#FFE691","#FFE690","#FFE590","#FFE590","#FFE590","#FFE590","#FFE590","#FFE58F","#FFE58F","#FFE58F","#FFE58F","#FFE58E","#FFE58E","#FFE48E","#FFE48C","#FFE48C","#FFE48C","#FFE38C","#FFE38C","#FFE38C","#FFE38C","#FFE38B","#FFE38B","#FFE38A","#FFE28A","#FFE289","#FFE289","#FFE188","#FFE188","#FFE188","#FFE188","#FFE187","#FFE187","#FFE187","#FFE187","#FFE186","#FFE186","#FFE186","#FFE186","#FFE086","#FFE086","#FFE085","#FFE085","#FFE085","#FFE084","#FFE084","#FFE084","#FFDF84","#FFDF84","#FFDF83","#FFDF82","#FFDF82","#FFDF82","#FEDE80","#FEDD7F","#FEDD7F","#FEDD7F","#FEDD7F","#FEDD7E","#FEDD7E","#FEDD7E","#FEDD7E","#FEDC7D","#FEDC7D","#FEDC7D","#FEDC7D","#FEDB7B","#FEDB7B","#FEDB7A","#FEDB7A","#FEDB7A","#FEDA79","#FEDA78","#FEDA78","#FEDA78","#FEDA78","#FEDA78","#FEDA77","#FEDA77","#FED977","#FED976","#FED976","#FED975","#FED875","#FED875","#FED875","#FED875","#FED875","#FED875","#FED874","#FED673","#FED673","#FED673","#FED673","#FED673","#FED673","#FED572","#FED572","#FED471","#FED471","#FED471","#FED370","#FED370","#FED370","#FED26F","#FED16E","#FED16E","#FED16E","#FED16D","#FED06D","#FED06C","#FECF6B","#FECF6B","#FECF6B","#FECF6B","#FFCE6A","#FFCE6A","#FFCD69","#FFCD69","#FFCD69","#FFCC68","#FFCC68","#FFCC68","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB66","#FFCB66","#FFCA66","#FFC965","#FFC965","#FFC965","#FFC864","#FFC864","#FFC864","#FFC864","#FFC863","#FFC763","#FFC762","#FFC662","#FFC560","#FFC560","#FFC460","#FFC460","#FFC45F","#FFC35F","#FFC35F","#FFC35E","#FFC35E","#FFC35E","#FFC35E","#FFC35E","#FFC35E","#FFC25D","#FFC15C","#FFC15C","#FFC15C","#FFC05B","#FFC05B","#FFC05B","#FFBF5A","#FFBF5A","#FFBE59","#FFBD58","#FEBD58","#FEBD58","#FEBC57","#FEBB56","#FEBA54","#FEBA54","#FEB953","#FEB853","#FEB853","#FEB852","#FEB752","#FEB752","#FEB751","#FEB651","#FEB651","#FEB650","#FEB650","#FEB650","#FEB550","#FEB550","#FEB54F","#FEB54F","#FEB44F","#FEB34D","#FEB34D","#FEB14C","#FEB14B","#FEAF4B","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAC49","#FEAC49","#FEAB49","#FEAB49","#FEAB49","#FEAA48","#FEAA48","#FEA948","#FEA948","#FEA948","#FEA847","#FEA747","#FEA647","#FEA646","#FEA546","#FEA546","#FEA446","#FEA345","#FEA144","#FEA144","#FEA144","#FE9E43","#FE9C42","#FE9C42","#FE9C42","#FE9B42","#FE9A41","#FE9A41","#FE9941","#FE9941","#FE9941","#FE9840","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD943F","#FD933E","#FD933E","#FD933E","#FD903D","#FD903D","#FD8F3D","#FD8E3C","#FD8E3C","#FD8E3C","#FD8D3C","#FD8D3C","#FD8C3C","#FD8A3B","#FD8A3B","#FD883A","#FD883A","#FD873A","#FD8138","#FD7F37","#FD7E37","#FD7E37","#FD7E37","#FD7935","#FD7835","#FD7634","#FD7233","#FD7033","#FD6F32","#FD6E32","#FD6C31","#FD6B31","#FD6931","#FD6930","#FD5B2D","#FC592C","#FC562C","#FC542B","#FC4F2A","#FB4D2A","#F94828","#F84828","#F84728","#F84728","#F13B24","#EC3121","#E41E1D","#DF181D","#D71320","#C60624","#C30425","#B10026","#960026","#800026"],"fillOpacity":0.6},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]},{"method":"addLegend","args":[{"colors":["#FFFFCC , #FFFEC9 0.738788253542188%, #FFE794 16.2104586232323%, #FFC460 31.6821289929223%, #FD9640 47.1537993626124%, #FC4E2A 62.6254697323025%, #D9151F 78.0971401019926%, #9F0026 93.5688104716827%, #800026 "],"labels":["0 - 5","5 - 10","10 - 15","15 - 20","20 - 25","25 - 30"],"na_color":null,"na_label":"NA","opacity":1,"position":"bottomright","type":"numeric","title":"Avg. Daily NO2 (ppb)","extra":{"p_1":0.00738788253542188,"p_n":0.935688104716827},"layerId":null,"className":"info legend","group":null}]}],"limits":{"lat":[18.198712,48.64193],"lng":[-124.20139,-66.052237]}},"evals":[],"jsHooks":[]}</script><!--/html_preserve-->

I'm curious to see how similar maps displaying the AQI and O$_3$ in a similar way. We already have the AQI data but let's load in O$_3$ and take a look at that.


```r
o3_df <- read_csv('data/daily_44201_2017.csv')
```


```r
#--> Create a unique identifier based on state, county codes, and site number
o3_df %>%
  mutate(Identifier = paste(o3_df$'State Code', o3_df$'County Code', 
                            o3_df$'Site Num', sep = '-')) -> o3_df

#--> Number of unique sensors
length(unique(o3_df$Identifier))
```

```
## [1] 1265
```
There are 1265 sensors measuring ozone in the US. We'll do a similar pipeline to what we diw with Nitrous Dioxide to create a map showing where Ozone levels are highest.


```r
#--> Make variable names DPLYR friendly
o3_df <- rename(o3_df, 'DailyMeanPPB' = 'Arithmetic Mean')

#--> Take out Alaska, Hawaii, Puerto Rico
o3_df %>%
  filter(!('State Name' == 'Alaska')) %>%
  filter(!('State Name' == 'Hawaii')) %>%
  filter(!('State Name' == 'Puerto Rico')) %>%
  filter(DailyMeanPPB > .01) %>%
  filter(Longitude > -142) -> o3_df

#--> Compute the yearly mean Ozone
o3_df %>%
  group_by(Identifier) %>%
  summarise_at(vars('DailyMeanPPB'), mean) %>%
  ungroup() -> daily_mean_o3_df

#--> Compute a yearly mean AQI
o3_df %>%
  group_by(Identifier) %>%
  summarise_at(vars('AQI'), mean) %>%
  ungroup() -> daily_mean_AQI_o3_df

#--> Join the unique sensors, yearly NO2 ppb, and coordinates
o3_df %>%
  ungroup() %>%
  select('State Name', 'City Name', 'Identifier', 'Latitude', 'Longitude') %>%
  full_join(daily_mean_o3_df, by = 'Identifier') %>%
  distinct() %>%
  full_join(daily_mean_AQI_o3_df) %>%
  distinct() %>%
  rename('DailyMeanAQI' = 'AQI') -> daily_mean_o3_df

rm(daily_mean_ppb_o3_df, daily_mean_AQI_o3_df)

head(daily_mean_o3_df)
```

```
## # A tibble: 6 x 7
##   `State Name` `City Name` Identifier Latitude Longitude DailyMeanPPB
##   <chr>        <chr>       <chr>         <dbl>     <dbl>        <dbl>
## 1 Alabama      Fairhope    01-003-00~     30.5     -87.9       0.0305
## 2 Alabama      Muscle Sho~ 01-033-10~     34.8     -87.6       0.0266
## 3 Alabama      Crossville  01-049-99~     34.3     -86.0       0.0329
## 4 Alabama      Wetumpka    01-051-00~     32.5     -86.2       0.0228
## 5 Alabama      Southside   01-055-00~     33.9     -86.1       0.0281
## 6 Alabama      Dothan      01-069-00~     31.2     -85.4       0.0255
## # ... with 1 more variable: DailyMeanAQI <dbl>
```

Now we have two dataframes--daily_mean_no2_df and daily_mean_o3_df. These both contain their respective daily averages of their pollutants in ppb. They also both contain AQI measurements. Let's map Ozone the way we did with Nitrous Dioxide. Then we'll map AQI and put all three in a grid.


```r
#--> Create an sf compatable data type
daily_mean_o3_df <- daily_mean_o3_df[order(daily_mean_o3_df$DailyMeanPPB), ]
daily_mean_o3_sf <- st_as_sf(daily_mean_o3_df, coords = c("Longitude", "Latitude"))

#--> Color spectrum
Npal2 <- colorNumeric(
  palette = "YlOrRd", n = 10,
  domain = daily_mean_o3_sf$DailyMeanPPB
)

#--> Make our map
o3_circles_map <- daily_mean_o3_sf %>%
  leaflet() %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
  addCircles(radius = daily_mean_o3_sf$DailyMeanPPB*2000000, fillOpacity = .6, 
             fillColor = Npal2(daily_mean_o3_sf$DailyMeanPPB), stroke = FALSE) %>%
  addLegend("bottomright", pal = Npal2, values = ~DailyMeanPPB, 
            labFormat = function(type, cuts, p) {
              n = length(cuts) 
              paste0(prettyNum(cuts[-n], digits=0, big.mark = ",", scientific=F), 
                     " - ", prettyNum(cuts[-1], digits=0, big.mark=",", scientific=T))},
            title = "Avg. Daily O3 (ppb)", opacity = 1)

o3_circles_map
```

<!--html_preserve--><div id="htmlwidget-fc8984674e577df161b0" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-fc8984674e577df161b0">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["Stamen.TonerLines",null,"Basemap",{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addProviderTiles","args":["Stamen.TonerLite",null,"Basemap",{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[18.440774,37.362137,37.864767,41.726892,34.325318,32.362606,18.420089,35.4884,29.758889,48.52059,40.92458,40.776944,32.538364,37.814781,45.393497,29.828086,29.625556,38.8795,38.895572,29.99497,38.403765,33.089772,41.442778,33.213611,48.95074,37.743065,34.474526,43.8345,33.81468,33.6878,42.385998,37.4826,37.765946,47.568236,44.965242,37.97231,29.767997,25.892518,30.439722,37.482934,33.545278,41.965193,32.364565,30.085263,37.9604,40.008889,32.668987,39.787933,38.548136,38.310942,40.720989,30.681718,29.686389,30.419805,31.188933,33.553056,35.0608,38.62901,29.834167,38.346258,43.660246,29.802707,26.22621,34.1795,33.331111,30.057515,30.204051,30.700895,34.949147,47.5525,44.026312,40.67025,30.227798,30.848611,37.28329,34.851537,47.49022,30.315406,45.496641,29.764098,40.043833,30.1103,40.816,30.036422,30.429381,33.3169,30.770181,33.612406,32.329111,33.578333,33.8025,30.229653,41.705226,29.489083,29.733726,34.402773,36.983921,33.485556,38.102507,40.81976,41.265556,26.200335,30.477725,28.45445,35.498711,43.68578,42.605816,34.762619,30.7017,26.053889,27.939746,29.623889,30.178056,30.201111,43.629605,33.386389,42.930521,40.51408,30.378217,37.687526,37.348497,32.805264,29.863957,30.500642,36.060833,38.612034,29.192754,44.155636,34.01194,39.101439,43.608056,40.692224,30.461981,44.80353,38.23887,33.40405,27.350278,46.933754,41.52375,29.670025,32.509959,29.566112,35.434767,29.901036,36.495767,36.69676,40.747796,27.517449,37.950741,34.364167,33.4339,40.272222,33.582044,41.479116,40.8679,26.073536,40.246992,33.007866,34.9127,40.36644,30.140265,26.270083,39.14566,38.508075,46.952562,32.346722,33.588545,42.718653,42.3295,29.043759,39.01893,32.987252,34.63782,42.386811,25.587327,40.283092,29.170533,40.535278,40.309722,40.146667,34.756189,43.9731,41.855243,27.449763,40.452913,43.944519,27.633089,45.768531,29.695729,35.721095,30.4747,27.089194,38.650783,26.088421,35.40814,36.209286,40.277647,28.332225,43.974622,40.515262,45.168004,45.616667,28.347509,48.5103,29.723333,41.492117,41.3014,31.954286,29.9425,27.832409,33.9039,28.090299,36.205055,32.68336,34.002747,38.45934,29.978926,38.53445,37.04926,38.558228,40.628056,34.44551,39.055277,40.38335,30.260278,42.22862,38.47753,36.804669,27.928356,41.784722,46.81826,40.73614,39.28102,38.013333,28.83617,28.028889,34.264917,30.039524,31.6675,35.96522,46.493633,40.995848,29.897516,44.81029,32.06848,37.743649,45.13768,38.194501,33.433949,39.422273,46.713694,43.656764,29.109151,41.530011,34.06659,39.965278,26.593808,29.939614,41.606667,39.810833,29.823319,41.2508,37.98629,35.197288,33.8005,39.991389,37.936013,32.412811,38.970092,34.530717,41.78555,40.304694,39.263914,40.462182,42.099699,27.172458,34.093959,30.221255,27.189215,35.49453,29.520443,36.46983,40.046667,36.60843,37.226862,35.50716,35.972347,47.948622,42.62668,38.654069,48.15278,46.602248,47.3132,39.024265,46.842181,38.47367,42.334982,39.0905,34.06703,41.096188,43.2185,42.770837,30.041238,44.377794,41.05192,29.275381,37.62668,39.21487,33.901389,37.35748,35.603056,36.844096,38.613779,38.302591,36.999571,33.4124,27.96565,30.426533,35.217501,31.169805,28.596389,40.107222,38.91833,39.448105,27.76534,29.583047,40.814183,36.922222,38.006311,34.376227,45.40184,27.785866,33.92513,39.138773,44.308132,28.053611,42.065106,33.9632,39.739444,36.29756,39.117219,34.751848,40.244913,32.378682,42.984173,41.45589,35.590833,44.791437,40.611944,39.0327,33.153088,37.55652,40.712778,40.337328,36.011703,40.170556,43.44957,41.08306,40.46542,45.549839,43.05235,27.946688,38.22876,41.849433,39.83562,29.632058,36.085508,44.7614,46.6041,32.941023,30.0925,32.466389,32.631231,39.0284,43.060975,39.835556,35.500102,34.285696,26.292025,41.615237,30.22611,40.811389,40.870436,36.150799,38.48123,39.533761,36.8071,30.088872,36.204902,32.676451,34.977,40.549985,30.300833,48.397787,33.83062,30.350302,45.402446,40.518735,38.339905,47.940861,41.18208,35.36631,37.702066,39.323533,32.46735,35.2401,37.09798,39.934446,34.772727,33.739963,37.079379,32.656357,34.52744,41.247486,33.746056,40.114876,34.427775,27.480873,34.605819,39.310833,32.536273,41.7514,41.603159,34.623236,33.0325,35.158686,40.82799,29.51509,39.327391,39.9878,38.838575,39.838119,36.66525,27.389079,28.523889,34.015436,42.88759,38.06091,41.322508,36.032955,37.1655,40.445278,43.58889,35.551868,32.820061,39.773889,35.988333,28.195574,42.68075,39.85567,40.05278,43.996908,34.10002,26.548212,46.825425,37.60613,41.094965,39.5513,40.112222,38.448672,40.71528,43.28428,43.54792,42.049148,32.175417,37.908533,39.202935,35.856111,27.740033,41.97677,41.670992,30.497478,38.656429,38.860669,38.424133,34.252378,46.851811,40.57747,39.114313,26.449247,41.221537,39.54182,46.39674,29.206667,38.66121,38.20087,41.69666,40.74529,33.918137,44.348604,35.231459,28.746111,44.473754,37.954444,37.34438,43.075371,43.14618,40.68742,38.307913,32.521272,44.310555,44.4438,35.9138,38.393822,30.525367,39.485987,34.988706,40.356694,48.41252,32.805818,39.96523,41.454597,40.984723,41.207958,34.448048,35.85408,42.751518,39.800339,40.3125,38.227066,48.317507,35.256577,41.984332,34.653606,38.358365,42.19438,41.874999,35.81066,36.708607,31.746775,40.617488,43.343167,35.151699,31.785769,43.600699,41.644067,37.93829,34.885608,36.89117,34.1326,30.394133,38.770081,39.77949,46.288877,41.832256,41.677667,33.37005,42.467573,29.727931,42.221442,35.438556,39.575634,38.71209,41.66812,42.51334,44.230622,37.8712,42.99328,41.514727,44.963633,42.281013,40.026037,36.742227,36.0388,42.738618,39.460478,39.540917,38.07657,39.12886,34.82166,41.639444,41.361856,43.016667,47.1411,30.483168,30.390369,42.743036,42.139996,47.41645,43.123704,39.866834,39.831522,38.6539,32.936523,38.921847,36.133802,34.687761,34.8848,43.566122,33.720742,39.761538,41.699174,41.716959,39.469219,43.7775,42.09142,36.019186,38.869001,47.5812,40.076389,30.354436,44.18089,35.935833,46.2053,39.07807,33.57454,35.03146,32.172995,39.751184,44.08747,32.564968,42.798339,45.20916,39.749027,25.732878,43.01209,33.219069,41.6175,33.9508,43.6138,37.47689,43.22386,47.298611,48.29786,37.281598,37.654456,45.25928,38.986672,33.45793,43.466111,37.155392,48.64193,38.81194,27.307268,38.49011,39.6359,36.1797,39.529444,41.206321,27.892523,34.46245,38.7408,34.835721,36.141875,35.4325,32.442304,30.378287,33.503833,39.68425,38.85287,39.210857,33.342226,44.531907,32.38082,35.750735,37.487981,34.05111,41.629167,33.47968,41.645381,38.745726,32.98426,40.0877,32.344008,46.0519,39.169533,37.897506,44.735978,42.14175,42.278067,42.862531,30.130433,43.561043,36.58211,41.4271,42.474642,37.67696,41.399167,36.707727,41.182466,40.816038,41.118333,33.362593,36.634225,38.587525,40.00103,42.274319,43.020075,33.48385,41.841039,40.427372,37.780776,39.432117,45.2066,32.204411,37.05822,42.2869,41.377685,40.7208,43.278061,33.801667,37.205862,39.384671,39.42276,33.40316,38.494475,35.314158,32.508306,38.920835,35.378153,41.420882,38.051667,35.953708,31.765685,34.289001,35.641276,36.307033,43.917955,41.215014,37.28342,41.945874,31.653074,36.35586,43.23086,33.410648,37.705612,42.060285,34.974039,40.969112,42.240565,37.13179,39.817222,35.2632,39.66575,34.153,44.53098,44.30738,39.410191,31.930659,36.191251,32.919206,38.7791,35.111944,40.300385,37.641583,41.106486,43.168336,35.631629,42.463063,39.834461,32.031934,39.474976,45.602419,39.5327,42.814412,36.48324,41.813049,36.141111,37.256137,32.482083,44.138619,39.758889,35.01708,40.959604,43.047224,38.13784,42.416636,32.845467,41.4942,36.91171,40.06483,43.953334,41.551667,42.51831,39.961111,40.684722,41.84046,36.867125,36.228408,39.328807,39.86097,39.649367,32.987891,35.159649,42.953336,36.90118,39.396075,45.565,40.310025,32.29515,43.836388,40.787628,34.131262,28.310841,42.731394,36.541365,34.615367,35.233476,44.980577,36.026,40.540455,45.366151,43.0034,40.253611,33.741242,39.464872,36.233274,33.1787,30.36805,41.685707,37.89147,39.789486,41.512118,39.4125,40.59664,44.52839,32.676186,36.109167,35.949765,41.1175,37.350054,44.70735,38.77335,39.858889,33.447867,36.306965,39.42689,44.37705,38.8577,43.4351,47.185833,42.19779,39.785644,32.922474,39.80933,44.307,44.28,38.082155,32.952124,39.558525,35.614131,36.110693,33.945379,36.7841,35.503587,38.872546,40.17093,31.768291,40.068297,42.49963,41.598119,39.02473,38.176278,35.331302,41.221418,43.687402,39.305021,40.386368,40.689253,38.4002,41.754722,39.997732,37.2385,31.122419,34.54166,43.100838,42.4006,38.508547,43.045269,43.1818,36.105481,39.564178,43.176672,29.254474,32.868773,41.240453,42.829154,34.210154,44.39308,38.06503,34.63298,35.002304,36.158414,33.080087,38.8994,34.895007,39.2787,44.616943,33.995638,40.93133,40.695078,33.590833,43.815596,33.29898,36.953256,41.285533,38.113889,36.705506,41.780261,40.82812,38.885528,35.479215,33.1324,32.690278,40.08502,36.308889,41.0604,42.8608,45.2384,36.031831,34.725538,36.512368,42.894451,42.580009,31.088002,35.320105,39.9428,40.002511,35.299484,43.3156,39.444294,41.058617,34.404268,47.803392,38.444971,39.613367,38.00641,39.294322,39.92002,36.332179,39.78819,32.954361,36.956222,39.70595,39.021881,47.8679,38.115152,34.805261,41.004657,35.477036,43.4981,39.9231,41.644722,39.417243,37.103733,38.201852,41.995568,41.959695,32.579361,42.298493,37.7046,34.276362,41.842649,36.819111,34.8147,39.563333,37.9214,46.8943,35.477801,37.69,42.211774,37.319186,38.683304,37.682512,27.8492,35.102638,32.789561,40.770944,41.976389,43.343,33.508125,39.067159,33.217025,33.99958,39.100174,39.621434,33.488242,39.407452,40.56333,34.14435,42.767786,35.35472,35.1343,39.525083,36.05097,45.440295,37.13678,34.10374,41.552196,35.832726,39.472471,32.353595,42.5958,41.55523,33.78942,41.35362,32.317593,39.166017,38.985578,38.890186,34.1365,38.536722,46.2756,45.828968,40.56252,44.6522,39.303174,41.726811,33.56033,41.975804,40.96078,41.330469,36.841331,41.717762,33.63003,38.70608,41.49511,42.43084,39.602787,33.474609,36.314399,34.226639,37.360684,39.0828,38.958341,38.75961,44.44312,41.821342,41.673006,41.669001,41.91056,42.86183,34.38344,41.30283,39.701444,41.13069,37.689615,36.048705,36.785322,41.89557,36.106389,38.342743,35.23668,39.331913,32.726656,39.1447,39.430038,36.105629,32.04767,36.59745,33.54549,35.356601,39.399837,39.43806,44.146964,39.04577,41.755832,31.893913,38.71085,34.454514,31.87952,34.510014,33.67649,40.084555,41.492707,40.736389,33.41045,41.256788,39.915409,42.8463,42.504722,37.10258,40.745504,43.667418,43.670833,37.90084,33.63713,40.070016,41.537069,39.53063,39.9544,37.981582,33.290229,42.062053,33.67464,40.902967,34.10688,36.1058,38.935578,32.79222,39.645264,31.796218,44.351697,34.19925,40.136336,46.8505,36.809735,34.48974,38.726573,40.038889,32.380118,41.1525,40.375644,36.807913,35.206111,40.600532,36.16976,39.250409,39.110539,37.70264,33.880812,43.74561,33.45223,37.179125,34.596095,42.778304,37.3297,33.71881,41.303614,40.216779,40.294178,42.229891,33.61103,42.486361,41.158,36.270592,42.82231,47.048537,39.130575,34.785219,39.638781,35.61975,42.869824,34.2439,43.101281,38.5231,39.567887,32.425261,33.4214,39.534488,42.7907,33.507992,40.592543,35.25793,44.36608,39.254449,34.8803,46.7841,32.041212,35.63348,44.933611,40.53999,36.173415,36.985119,42.719,41.182227,29.30265,35.785665,40.086944,40.4372,43.460556,35.562872,36.796667,46.204582,40.483598,35.763873,47.82728,38.853097,40.46471,43.873056,39.541515,34.671394,43.55764,41.515051,41.750556,43.577603,41.386944,39.743724,44.270093,39.638522,43.081667,35.587144,35.346094,35.696758,38.81161,33.9397,32.1783,31.787885,35.379167,36.357786,32.00941,40.496392,40.206291,40.05671,40.329253,34.82251,41.373097,33.6547,36.187742,34.05977,37.30389,35.64368,32.174538,33.82169,37.1983,35.978149,36.48947,39.60996,35.438869,42.373499,44.56536,33.70853,38.890941,35.765413,35.524544,38.725282,39.912799,35.1852,38.9564,33.293465,39.00512,39.240278,36.035,33.92086,37.71325,33.583333,34.418073,34.612055,37.1984,39.714041,33.706328,36.39103,32.842242,38.45832,33.85275,42.529999,36.569333,40.27813,36.508611,36.05864,35.050551,32.725226,42.9288,35.05443,39.205572,34.2431,41.3642,33.944713,33.9828,34.426126,37.549928,39.794391,18.177939,39.234331,36.567178,40.262072,36.318874,34.06957,33.7411,35.1019],[-66.126531,-118.417478,-122.302741,-122.633579,-82.386376,-88.277992,-66.150615,-97.090278,-95.079444,-122.61428,-75.067815,-124.1775,-86.232347,-122.282347,-122.747894,-95.284096,-95.267222,-80.8477,-76.958072,-90.817415,-122.818294,-87.459733,-75.623056,-115.54528,-122.55441,-122.169935,-85.408847,-123.0353,-80.781135,-84.2905,-83.266189,-82.53532,-122.399044,-122.308628,-93.254759,-122.520004,-95.220582,-97.49383,-84.346389,-122.20337,-86.549167,-87.876265,-88.731491,-93.761341,-122.356811,-75.09778,-94.167457,-86.13088,-82.731163,-122.296189,-74.192892,-91.366247,-95.294722,-91.182016,-85.423094,-86.815,-83.4306,-82.45886,-95.489167,-81.621161,-70.268965,-95.125495,-98.291069,-93.0988,-87.003611,-90.619286,-91.117384,-91.056068,-120.43763,-122.064722,-123.083737,-74.126081,-93.579965,-85.603889,-83.20932,-82.744576,-121.77278,-90.811383,-122.602877,-90.765275,-76.1124,-84.9903,-73.902,-94.071061,-90.199678,-86.825,-88.087761,-114.602886,-90.182722,-86.773889,-118.22,-90.965628,-76.512726,-81.276833,-95.257593,-119.458454,-121.989328,-86.915,-122.237976,-73.94825,-75.846389,-97.712684,-81.587339,-81.381181,-83.310242,-74.98538,-72.596689,-87.638097,-94.6742,-80.256944,-82.000084,-95.474167,-82.619167,-82.441111,-72.309499,-86.816667,-72.272332,-75.789721,-81.8409,-121.784217,-121.894898,-83.543493,-94.317802,-91.213556,-86.286261,-90.160477,-82.173149,-103.315765,-118.06995,-90.344494,-72.982778,-75.237156,-91.179219,-106.961763,-82.9881,-84.745728,-82.479722,-96.85535,-74.21534,-95.128508,-92.046196,-82.26608,-83.442133,-95.326137,-121.731571,-121.637182,-80.316442,-99.515219,-121.268523,-77.838611,-82.0224,-76.681389,-82.131249,-75.578186,-73.87809,-80.33845,-76.846988,-80.965038,-80.8745,-80.61558,-93.368448,-81.710959,-123.20298,-82.659241,-122.59527,-90.225667,-84.069608,-71.522416,-71.0826,-95.472946,-122.91333,-79.9367,-120.4575,-83.270506,-80.325922,-74.742644,-82.100646,-78.370833,-78.915,-79.902222,-92.281296,-74.2232,-87.75247,-82.522041,-122.298866,-71.700788,-82.54593,-122.7721,-95.499219,-84.343035,-88.1411,-82.362583,-121.506767,-80.111193,-94.524413,-121.126371,-74.0051,-82.305643,-70.124608,-74.806671,-92.765136,-122.516667,-81.636464,-113.99681,-95.635833,-81.678449,-72.902871,-84.08101,-94.000556,-97.55538,-86.0539,-82.700707,-86.74472,-93.861582,-89.799183,-82.64041,-94.010872,-121.7734,-86.21487,-121.492981,-75.341111,-119.8284,-76.878333,-75.9686,-81.453611,-83.2082,-78.81952,-94.725024,-82.454539,-72.631667,-92.08936,-73.82153,-78.08157,-87.577222,-97.00553,-81.972222,-88.766222,-95.673951,-106.288,-84.22316,-84.364207,-80.346442,-93.991084,-122.915085,-81.04942,-121.934188,-93.207615,-87.341396,-84.161811,-75.025204,-92.511722,-70.629138,-80.993666,-90.587611,-118.22688,-76.699444,-80.058492,-89.923883,-87.304722,-86.114444,-94.983786,-76.9238,-85.71192,-90.193141,-78.9941,-75.080833,-122.026154,-86.263394,-77.016715,-86.967536,-73.74136,-79.505667,-86.292269,-74.429439,-71.619399,-80.240689,-80.962304,-91.315418,-81.34035,-120.66617,-95.392509,-83.826511,-76.283333,-83.73694,-121.979675,-82.96337,-81.933072,-91.495574,-71.362068,-122.901857,-103.63951,-90.656141,-102.5273,-95.711275,-114.021499,-77.76772,-89.037775,-79.6617,-117.7514,-80.658867,-71.5145,-71.10229,-90.272826,-70.854697,-73.76366,-98.311692,-79.51257,-84.69086,-118.205,-77.59355,-83.783611,-121.362121,-121.368014,-121.420838,-121.574684,-111.93473,-82.2304,-86.666217,-90.019707,-81.495035,-81.3625,-74.882222,-84.852637,-77.963845,-97.434262,-95.015544,-79.56475,-94.838889,-121.641918,-84.059506,-93.20306,-82.739875,-117.95264,-121.618549,-71.217639,-80.628611,-71.012129,-84.0691,-75.558056,-86.653137,-94.635605,-82.256701,-88.188519,-94.711811,-85.671339,-73.70977,-78.461944,-93.512534,-75.4325,-122.92229,-96.115572,-77.40027,-81.598333,-76.383447,-94.167436,-80.261389,-74.51625,-75.32328,-79.960757,-94.13345,-76.05921,-82.731767,-85.65452,-93.697617,-84.720524,-98.564936,-83.764806,-91.143,-68.4135,-79.657187,-84.161111,-114.768611,-117.059075,-76.8171,-87.913504,-75.3725,-82.59986,-79.744859,-80.09647,-71.72,-92.042908,-77.877028,-73.991994,-86.623297,-77.3704,-122.191903,-108.69523,-91.869595,-95.976537,-96.87206,-81.207,-122.382011,-89.395916,-122.504971,-117.93845,-95.425128,-122.854437,-88.996896,-120.763515,-101.571583,-74.02819,-120.84271,-97.314847,-81.552367,-85.083447,-80.785683,-84.61152,-75.125291,-86.756174,-81.853635,-121.600031,-97.088585,-120.1965,-95.973142,-90.723028,-80.700972,-119.691218,-82.618709,-120.075069,-76.474444,-93.74894,-87.713488,-93.643118,-82.532059,-115.62361,-78.728035,-73.05754,-98.620166,-94.95102,-79.2515,-94.746424,-104.94984,-76.73078,-80.311033,-81.723333,-84.607423,-73.24984,-85.89804,-95.938593,-78.904037,-78.3069,-80.420833,-70.87734,-80.395039,-96.860117,-75.496389,-77.582778,-82.756264,-73.75733,-83.99773,-88.37251,-92.450366,-117.49201,-81.981523,-100.76821,-77.2188,-85.101816,-75.732,-75.309167,-90.395904,-124.20139,-76.46324,-96.700769,-88.273029,-96.870189,-80.632633,-122.017728,-78.574167,-82.465146,-91.68766,-87.732457,-87.880258,-90.198348,-90.105851,-82.4259,-119.143176,-95.846272,-105.07892,-77.106876,-81.939256,-88.190967,-107.784125,-94.1303,-81.0525,-121.73269,-77.37742,-86.214722,-73.41919,-83.344385,-96.807299,-77.568792,-81.310556,-93.012611,-87.321667,-77.25925,-70.748017,-77.54817,-89.606943,-85.834313,-84.944635,-84.891865,-95.81789,-81.191,-85.664118,-87.20355,-87.401312,-82.075802,-83.063971,-92.829225,-97.356568,-82.95549,-80.589612,-96.677513,-95.945897,-119.231321,-94.985964,-96.707208,-75.212119,-74.8729,-122.075624,-107.862471,-120.669861,-87.792002,-82.838659,-121.950003,-72.555112,-90.177574,-76.906249,-86.566284,-106.402806,-79.727664,-70.471034,-89.850249,-106.323578,-116.347853,-83.54616,-86.89719,-95.78441,-81.25423,-118.1272,-87.008033,-99.763424,-105.00518,-85.950227,-95.928185,-108.024835,-112.6207,-87.810047,-93.894081,-88.242207,-81.27675,-86.477893,-121.38109,-87.99057,-83.005971,-69.785,-87.46375,-78.77153,-90.51735,-67.060728,-91.526879,-82.432996,-107.977567,-85.7331,-84.534633,-76.633543,-119.746761,-78.50397,-84.50404,-89.98783,-87.493611,-81.86463,-87.933333,-121.9379,-97.872301,-89.049778,-92.513241,-87.799227,-117.52997,-94.693518,-88.925594,-89.640926,-75.6106,-96.459211,-77.013178,-95.764537,-86.586362,-76.6203,-71.496335,-84.357316,-121.84162,-90.521944,-85.824696,-119.775354,-91.2269,-77.20978,-83.87381,-89.622816,-103.2995,-75.011944,-97.760255,-85.738985,-81.530278,-93.75945,-92.31626,-112.19196,-120.50103,-110.980134,-104.987625,-75.97316,-96.317687,-84.393795,-93.66921,-86.186269,-80.16175,-73.6489,-97.196284,-87.199167,-118.43043,-83.3591,-97.366399,-78.47888,-101.766944,-124.62491,-120.434992,-122.031547,-122.588151,-75.5568,-112.04601,-88.621111,-88.394024,-102.4018,-76.74417,-82.570376,-90.70509,-83.2605,-94.116827,-84.393453,-111.975524,-82.538429,-120.02551,-87.4853,-92.260581,-115.078742,-79.2887,-97.803529,-88.53393,-112.095767,-74.861491,-77.63462,-87.668297,-81.788731,-67.59587,-111.12716,-94.669697,-120.837005,-118.45636,-86.684444,-111.91721,-70.897504,-121.266312,-97.063721,-82.959773,-95.415752,-89.654,-76.627933,-97.492083,-68.670752,-80.038611,-85.54189,-71.38014,-85.731517,-70.207324,-82.485742,-80.1451,-70.970816,-95.47594,-73.443056,-93.222,-81.330486,-85.661408,-73.336667,-117.09023,-120.382331,-76.141006,-83.80456,-71.875511,-88.21507,-112.14257,-71.36097,-80.592318,-87.075307,-81.460443,-90.5969,-110.878067,-88.57251,-89.9997,-83.611104,-77.9319,-86.311083,-86.9425,-107.254118,-84.540537,-77.37519,-112.07533,-121.211131,-80.713469,-111.308056,-86.080523,-89.83447,-82.095729,-87.278056,-96.004975,-106.455227,-85.970065,-77.360126,-79.467417,-69.26059,-80.484779,-79.88452,-112.233973,-97.070698,-96.01243,-77.17136,-96.94459,-85.852629,-87.863225,-80.540622,-95.044951,-83.599602,-86.142953,-75.563889,-79.8365,-83.94268,-95.3213,-87.90799,-88.395178,-76.296946,-106.631103,-115.122953,-96.808498,-75.16323,-98.252778,-85.245862,-120.994622,-81.503547,-83.461541,-120.690977,-83.183199,-75.768242,-96.399141,-91.788991,-121.203387,-84.7286,-70.817783,-121.15688,-88.072827,-78.768056,-93.299894,-97.026899,-87.6161,-86.398611,-106.65739,-85.37961,-83.670159,-85.57648,-83.902185,-117.123894,-83.718949,-87.323337,-74.44405,-86.294415,-86.370556,-89.06347,-77.475556,-80.359722,-72.010368,-120.010158,-95.249943,-76.553075,-76.462055,-79.920867,-97.477175,-97.473794,-82.456229,-76.43808,-89.809739,-88.8086,-82.691724,-110.9823,-82.6429,-74.676301,-80.868318,-80.61533,-82.793463,-82.424555,-80.198787,-85.181581,-74.695005,-80.342,-86.553035,-106.48982,-88.8283,-111.663056,-84.776429,-74.448736,-119.766212,-84.4052,-87.270967,-71.169235,-84.58825,-86.06085,-87.036236,-107.23056,-74.12525,-72.86884,-115.484144,-79.801111,-87.138246,-78.526194,-108.592334,-89.77183,-77.10468,-86.021389,-117.088649,-79.09197,-84.20077,-68.2609,-77.05922,-89.6797,-101.428056,-86.309694,-84.134412,-97.282088,-80.26567,-86.242649,-108.041111,-88.624943,-117.264088,-87.312883,-97.475083,-80.226438,-96.405726,-87.8499,-119.272606,-90.226488,-122.25556,-106.50126,-85.992451,-79.31881,-78.767867,-77.48925,-89.788459,-119.000974,-85.016821,-88.422045,-75.797317,-104.73744,-122.402194,-85.44428,-86.11,-86.395394,-94.42468,-97.431052,-119.79146,-89.357298,-76.6538,-76.811864,-70.713958,-87.901,-96.361196,-77.720244,-85.416608,-94.861289,-97.905931,-80.66272,-97.854129,-118.870496,-73.8589,-84.49761,-98.42879,-78.991692,-98.931973,-111.739999,-90.44917,-117.024484,-84.36625,-86.109408,-117.493304,-81.123519,-92.006318,-116.088333,-87.792235,-111.88431,-120.034203,-93.583983,-87.536667,-119.741966,-95.948435,-81.3785,-121.303144,-97.751503,-96.786419,-114.61444,-84.113808,-79.859167,-81.9239,-106.23586,-86.994,-119.055018,-120.428774,-95.882622,-85.852734,-88.499046,-97.679734,-97.484099,-81.3373,-85.656391,-106.548914,-89.1089,-77.042252,-74.255544,-118.809946,-104.485552,-76.111274,-85.870669,-87.718354,-85.766816,-77.30968,-119.291228,-83.47606,-111.76225,-97.03135,-79.012,-84.47445,-104.676944,-86.60325,-83.2377,-73.585128,-97.494309,-87.81,-77.3078,-76.939167,-86.152363,-76.387017,-120.681567,-83.946559,-80.572808,-116.929486,-72.334079,-85.0485,-118.683757,-111.852199,-119.717356,-106.7396,-76.203889,-83.0662,-103.37853,-97.303044,-94.035,-71.11397,-93.204411,-121.164457,-121.443324,-80.4554,-85.162194,-116.944222,-84.0539,-72.388056,-87.92,-111.83852,-88.548934,-117.396158,-117.41601,-120.953832,-119.71877,-111.855654,-94.265373,-78.919972,-117.85036,-86.148577,-120.04019,-106.5852,-119.807717,-80.143657,-105.370283,-107.62863,-117.62914,-72.630015,-93.20826,-118.783624,-97.436742,-87.8858,-81.575256,-117.22764,-72.07882,-106.768337,-120.148833,-86.99012,-90.148031,-117.92391,-76.617194,-116.0216,-119.262991,-80.503948,-105.2903,-94.377014,-81.242156,-112.06626,-70.023598,-72.71238,-70.785225,-119.875415,-86.907786,-117.67593,-92.09308,-71.423705,-83.000138,-119.247741,-111.805769,-119.64457,-98.03544,-118.330783,-84.1441,-104.817215,-94.57983,-87.50524,-73.297257,-81.422455,-83.28717,-91.652121,-71.878626,-118.5284,-105.586,-75.860051,-104.75308,-121.631916,-115.052942,-119.774174,-86.001629,-115.253333,-108.99495,-118.789424,-94.580931,-103.122917,-119.7661,-83.788502,-83.602077,-110.774357,-119.504569,-111.60925,-119.063542,-119.739606,-108.02611,-105.529994,-90.84927,-87.54535,-106.425827,-90.47606,-94.143521,-110.99644,-117.331433,-117.33098,-82.81555,-112.018863,-111.872222,-111.86507,-72.55327,-91.335868,-106.27767,-87.8093,-107.870219,-89.585869,-87.716213,-110.599472,-90.42388,-112.34184,-105.220238,-81.45879,-94.55594,-94.849,-120.379611,-112.160597,-87.675254,-117.92568,-111.884467,-117.27411,-82.0454,-121.100648,-115.56306,-119.840025,-106.584434,-68.22698,-118.53276,-111.660502,-111.987164,-107.652192,-120.04692,-89.959963,-107.8475,-104.262726,-73.103056,-80.169943,-114.060879,-111.652777,-112.353414,-115.263038,-119.956738,-90.32408,-89.69864,-97.275896,-101.941218,-111.73331,-113.305096,-120.631282,-87.796138,-80.5578,-111.67183,-111.987871,-110.182742,-110.009732,-122.7877,-111.72529,-110.098861,-108.619,-115.238282,-106.36501,-109.455315,-108.313835,-84.626423,-105.13948,-106.07968,-109.87076,-113.5586,-105.498931,-78.43471,-104.957193,-111.06352,-111.5436,-105.070358,-110.0551,-111.755334,-105.141122,-83.79562,-73.90312,-76.424386,-101.6649,-121.740367,-106.40971,-83.941606,-106.847222,-121.57646,-115.332728,-119.658339,-109.753,-104.778334,-103.17781,-115.357087,-108.761389,-109.3047,-113.562222,-83.497941,-108.473138,-119.243743,-109.906796,-117.397004,-117.27422,-104.901289,-109.561472,-104.191944,-105.29841,-118.131456,-103.48386,-81.249906,-109.788333,-116.178156,-107.616667,-105.177989,-71.303821,-104.569335,-107.549444,-83.074156,-118.852037,-83.609612,-120.033084,-115.4108,-104.4406,-106.683324,-82.7925,-115.362234,-109.38906,-112.036298,-109.353932,-109.688108,-108.49424,-109.89249,-111.042376,-111.1074,-106.698369,-117.14731,-107.484167,-120.23135,-110.737116,-112.01739,-113.1506,-114.846313,-118.82915,-110.800749,-119.016765,-109.560498,-110.40034,-116.21537,-121.003373,-82.264944,-83.235981,-120.821916,-105.188587,-106.50815,-106.9858,-111.285594,-114.21593,-105.983056,-107.904167,-116.85841,-119.7062,-117.083333,-117.285597,-112.463213,-108.49046,-121.618836,-111.855622,-114.907429,-116.768225,-109.82126,-116.54101,-108.720003,-115.676651,-105.54564,-116.847778,-112.18358,-118.147294,-116.365203,-109.788,-119.404826,-121.820362,-117.27235,-106.2399,-116.830074,-111.7987,-117.563939,-119.844591,-105.76398,-65.915482,-121.056591,-118.778995,-122.092766,-115.586128,-116.38893,-115.8206,-115.7767],[32983.1508379888,40667.2132352941,41050.1768707483,41795.0322580645,42353,43373.7889908257,43424.0895522388,43843.3333333333,43884.3741007194,44220.7132867133,44327.0222222222,45429.4207317073,45506.1255605381,45788.2244224422,45966.958490566,46141.8187311178,46392.6099706745,46434.0647058824,46726.6728971963,46795.4695121951,46878.2987804878,47586.2978723404,47641.1876923077,47808.2259136213,47880.4342857143,48098.0235294118,48143.2881355932,48306.5657894737,48336.0787878788,48393.3333333333,48618.3344051447,48808.6416666667,48882.2314540059,48885.5215946844,49366.7847222222,49395.2985507246,49554.1650793651,49636.0344827586,49722.5375722543,49743.445482866,49898.8132780083,49996.6622516556,50084.041322314,50345.8112094395,50390.2305475504,50470.8181818182,50471.9093484419,50530.9240121581,50591.1363636364,50697.6555891239,50721.4954407295,50759.5593220339,50778.6976744186,50821.8983050847,50901.9495798319,50926.173374613,50929.0029498525,51124.3277310924,51152.081871345,51185.3735632184,51249.2528089888,51257.8674351585,51292.308988764,51391.3665689149,51463.5702479339,51465.7119113573,51518.5014245014,51531.3669467787,51537.5694444444,51556.5850340136,51565.4901960784,51581.8558558559,51728.8757062147,51791.7422969188,51849.695473251,51856.7985347985,51933.610738255,52010.988372093,52046.1130742049,52054.0279329609,52114.7645259939,52138.8653295129,52203.8353658537,52210.7942028985,52344.6050420168,52404.8451882845,52407.0822510822,52426.2125,52436.357771261,52454.7190082645,52542.3123123123,52581.2549019608,52637.9887640449,52699.782729805,52736.7803468208,52741.1220930233,52805.4191780822,52926.8395061728,52935.1428571429,52946.1717791411,52947.1213872832,53000.5817174515,53047.0459770115,53051.2528735632,53051.7184466019,53051.9488817891,53127.9533527697,53153.720164609,53180.6279069767,53248.4367816092,53251.8624641834,53293.1253644315,53351.8222222222,53366.8700564972,53375.8757062147,53378.1327433628,53461.1737891738,53508.2994011976,53548.1751412429,53585.1930835735,53596.8167202572,53654.8979591837,53669.7797101449,53672.7670454545,53686.8870292887,53773.496969697,53819.1057401813,53832.1344537815,53853.2571428571,53857.0714285714,53876.3556851312,53897.4567901235,53914.4011142061,53944.9043478261,53956.2612244898,53977.6150627615,53993.5,54021.6589595376,54042.7089337176,54115.5575221239,54119.4150417827,54178.814159292,54242.0633484163,54248.298245614,54309.3204419889,54342.5589041096,54350.284057971,54364.7529411765,54374.9061488673,54379.0042553192,54382.1557377049,54424.6424242424,54491.237704918,54537.1778425656,54564.0821114369,54584.3082437276,54607.5802469136,54655.0551724138,54688.6068376068,54727.9508196721,54739.4972375691,54746.3910614525,54758.0738461538,54802.631147541,54818.3660130719,54821.9020408163,54837.0756302521,54887.9052132701,54903.5014005602,54929.1497005988,54930.938547486,54967.2113821138,54971.1444444444,54976.1829652997,54995.9680511182,55009.4577259475,55057.8857142857,55097.0060240964,55146.221574344,55148.9577464789,55166.2662889518,55172.4189944134,55225.7258566978,55232.9329608939,55246.7548638132,55264.9802816901,55355.4189944134,55401.9867549669,55405.4210526316,55512.8260869565,55545.7918552036,55563.9770114943,55577.5724137931,55719.9715099715,55746.3629893238,55782.3701657459,55792,55794.0639534884,55801.0170940171,55813.6261127596,55841.8833333333,55901.0198675497,55943.2602739726,55943.8072289157,55994.8513119534,55995.8270893372,56030.2766570605,56058.575,56073.1036414566,56074.7521367521,56129.479338843,56228.418079096,56249.0923694779,56263.4127906977,56268.1196581197,56270.7786885246,56277.9375,56287.6823529412,56312.5901639344,56410.3024691358,56446.502994012,56465.8491620112,56532.8265895954,56550.6846846847,56577.6112676056,56578.7857142857,56580.6204081633,56599.7836065574,56600.6526946108,56622.2170087977,56632.7058823529,56701.6023738872,56731.7729257642,56778.0857142857,56853.3764044944,56885.0934065934,56891.9349593496,56912.3333333333,56912.9491525424,56914.5892116183,56921.7004405286,56970.0802292264,56970.6858789625,56980.3137254902,56993.3583333333,57068.7136929461,57101.3238636364,57111.6765957447,57144,57163.3072625698,57185.3568281938,57226.9502262443,57227.8413597734,57240.8936781609,57277.899408284,57289.5074183976,57305.6541786743,57307.7994428969,57382.4365781711,57430.2492753623,57457.6239316239,57461.9879518072,57464.1034482759,57480.0677966102,57485.3295774648,57527.2407407407,57546.0529411765,57554.3,57626.1360946746,57632.7983193277,57645.4712643678,57654.1310541311,57668.2060085837,57680.649122807,57718.8421052632,57738.9070422535,57760.5459610028,57761.4285714286,57766.6902654867,57788.2049861496,57813.6878612717,57850.4228571429,57861.0654761905,57873.162601626,57900.1916666667,57907.2133891213,57967.3666666667,57970.2288135593,57975.4929577465,58011.7765363128,58043.3184357542,58051.6343490305,58058.8184615385,58067.838150289,58096.9178082192,58103.756097561,58135.2979351032,58158.5953757225,58179.8888888889,58195.075,58204.1551246537,58208.0842696629,58208.2195845697,58224.1596958175,58246.3438395415,58252.7288135593,58271.631147541,58282.2212765957,58326.9520958084,58363.589958159,58380.7302904564,58416.8112676056,58456.6315789474,58469.5950920245,58472.7654320988,58481.7744807122,58486.2960893855,58513.9159663866,58542.7829787234,58564.4754098361,58589.1689750693,58618.427672956,58628.2533936652,58671.621399177,58692.1724137931,58722.8849557522,58724.5395894428,58725.3431734317,58733.2897727273,58733.9004149378,58760.5371900826,58766.6944444444,58768.2743902439,58773.5889570552,58793.9423076923,58818.2848837209,58827.1225071225,58845.4514767932,58857.224137931,58878.5528455285,58885.5976676385,58912.5730337079,58952.1473087819,58957.4535211268,58964.9915966386,58980.3844011142,58986.5528455285,58997.3277310924,59004.2117647059,59009.7613636364,59035.095505618,59037.1206896552,59037.762295082,59092.3342939481,59116.7619047619,59117.1884057971,59129.9329608939,59130.5779036827,59152.6880466472,59174.582278481,59187.1460055096,59193.3109243697,59207.1942857143,59209.71875,59227.2485875706,59227.527696793,59245.787755102,59258.3183673469,59267.955922865,59274.3573487032,59281.7752161383,59294.7019230769,59326.6777777778,59344.3440233236,59371.3937677054,59379.426035503,59478.631147541,59491.476702509,59539.462295082,59542.7920792079,59560.364640884,59574.0405797101,59578.6875,59587.808,59588.5,59592.6934097421,59609.4540059347,59612.9173789174,59622.9482758621,59627.9648093842,59666.0692041522,59672.9361702128,59683.6050420168,59690.8962655602,59691.9416909621,59693.1878453039,59698.5620915033,59704.2865329513,59756.3185840708,59792.7112462006,59797.8929577465,59801.9833333333,59811.2541254125,59826.2540983607,59832.3553719008,59872.8820224719,59883.9755102041,59902.2973760933,59921.1300813008,59931.8246753247,59944.6550218341,59970.1412429378,60021.56,60023.0028818444,60032.9090909091,60046.4552845528,60086.9121813031,60157.0879120879,60185.7938718663,60186.9532163743,60195.9718309859,60214.0323624595,60235.9856321839,60242.8669201521,60245.1578947368,60246.5447154472,60249.1833333333,60263.7117647059,60323.0909090909,60343.6694214876,60382.3426966292,60426.4756097561,60429.7306122449,60465.2034883721,60478.4109589041,60484.3836734694,60497.3732193732,60497.9588477366,60513.9330543933,60520.9469387755,60526.3988764045,60532.2478873239,60543.0316742081,60543.1267605634,60574.4156626506,60673.8218390805,60686.8524590164,60716.01179941,60716.5561797753,60752.3703703704,60783.6910112359,60838.6363636364,60905.4310344828,60908.5619834711,60919.65,60930.5606694561,60941.5014164306,60943.4533762058,60947.1384615385,60947.145194274,60961.3390804598,60967.5659340659,60969.1686046512,60973.1437125748,60975.1008645533,60985.3795918367,60998.8385093168,61014.7988668555,61044,61054.1306122449,61077.4777070064,61078.5150214592,61095.6709219858,61106.3661971831,61115.1721311475,61135.5397260274,61142.7190082645,61144.4057971014,61230.5867768595,61249.0335195531,61275.6976744186,61300.9510086455,61309.1583333333,61310.5835694051,61319.3474320242,61342.2612244898,61342.7100591716,61375.039039039,61382.1475409836,61383.404494382,61394.9098360656,61417.7927170868,61428.0823045267,61444.2448979592,61470.6008230453,61486.0501392758,61550.2307692308,61556.7025495751,61556.9916666667,61571.6897959184,61576.5205479452,61612.3697478992,61633.8461538461,61676.2,61700.0877192982,61709.6091954023,61730.2822580645,61731.6625514403,61735.2601156069,61748.9310344828,61802.622406639,61826,61866.1762114537,61868.9781659389,61880.826446281,61886.0931899642,61889.0137741047,61890.4679245283,61898.7736389685,61960.5106382979,61971.3222222222,61993.1790633609,61996.2907488987,62017.0405904059,62018.7848837209,62039.9775910364,62057.1934156379,62073.1918367347,62095.525,62109.8592375367,62111.5027027027,62113.2716049383,62120.2542372881,62150.1685393258,62185.2154696133,62185.631147541,62204.2775510204,62220.1461988304,62225.9918367347,62330.8166666667,62378.5224719101,62383.7520661157,62402.5285285285,62435.0081300813,62455.9414225941,62496.5604395604,62527.1666666667,62529.7142857143,62578.5609756098,62585.0116959064,62615.9,62624.6666666667,62712.5723472669,62730.5064102564,62745.4522821577,62766.0578512397,62786.825,62794.7025495751,62797.0084507042,62867.0055555556,62880.9672131148,62899.0661157025,62928.5480225989,62941.82369146,62989.2680115274,63000,63023.9352941176,63032.2426778243,63077.6470588235,63165.7479674797,63183.3017241379,63184.0658436214,63184.4830508474,63209.8692810457,63219.7633802817,63230.7948717949,63271.4650205761,63283.6231884058,63300.948051948,63337.7469387755,63365.2333333333,63403.7994428969,63406.0511363636,63459.5168195719,63467.5184135977,63469.1092436975,63491.1219512195,63523.055393586,63536.6697674419,63539.7394957983,63543.5135135135,63544.6707317073,63563.8771929825,63568.1024096385,63581.7317073171,63708.4972067039,63716.1373390558,63718.73556231,63755.207977208,63783.6578171091,63805.3949579832,63819.0395136778,63829.0290456432,63841.7613168724,63867.5765199161,63870.209631728,63881.2219178082,63899.0807799443,63899.263803681,63899.5641791045,63901.9831460674,63911.1631799163,63913.4918032787,63915.6115702479,63925.7378917379,63934.2011173184,63938.3398328691,63945.2217573222,63949.8105849582,63982.3085714286,64038.9777777778,64041.8910505837,64059.3798219585,64060.4956268222,64074.0732394366,64118.7102040816,64162.08,64177.4084507042,64192.7853107345,64200.0278551532,64257.65,64296.3669467787,64343.4754098361,64356.8746518106,64359.0040650407,64374.9467787115,64417.1573033708,64427.2540983607,64428.8805031446,64440.006097561,64467.5180055402,64473.5694050991,64502.0169971671,64508.6863905325,64520.3137254902,64573.4893617021,64574.2343096234,64592.1498559078,64630.3616236162,64674.3697478992,64702.9421487603,64729.6617647059,64777.4907407407,64796.4418604651,64800.5590778098,64801.5764705882,64804.3856502242,64809.1588785047,64863.2057142857,64879.2011019284,64900.6666666667,64922.4101123596,64923.8683127572,64935.7206703911,64954.4303797468,64977.0530612245,64983.047318612,65010.4077669903,65020.3166666667,65044.2057613169,65049.3241758242,65050.3123287671,65056.1662049862,65189.1867219917,65240.9523809524,65247.5745856354,65253.4707520891,65271.1549295775,65271.3333333333,65278.4979591837,65281.4589665653,65283,65293.9232876712,65337.8079096045,65345.7355371901,65350.3346938776,65353.5182072829,65364.7088607595,65383.8583569405,65390.3102493075,65396.3428571429,65397.0416666667,65406.1219512195,65417.1168091168,65417.2564841499,65417.5346938776,65426.9907692308,65455.3551020408,65470.1333333333,65498.3673469388,65512.9593495935,65518.8846153846,65524.4049586777,65542.868852459,65545.9261363636,65549.9827586207,65581.787755102,65593.8666666667,65619.8766519824,65677.4356846473,65700.9387755102,65712.9469387755,65717.8418079096,65725.0833333333,65729.1731843575,65731.4471544715,65732.6970954357,65736,65762.2044198895,65767.5102040816,65770.0769230769,65774.8404255319,65775.6225352113,65785.498392283,65811.2099447514,65841.1358024691,65850.7983539095,65870.2100840336,65876.2258726899,65957.1522633745,65964.1487603306,65966.6445783133,66031.7981651376,66034.6363636364,66043.6131386861,66048.5882352941,66054.1610169491,66054.7591836735,66055.3095890411,66057.2817337461,66103.811965812,66125.3165266107,66135.3274336283,66149.3032786885,66170.6411764706,66174.893442623,66175.0946502057,66190.5423728814,66201.05,66315.2754491018,66324.9213483146,66340.9831460674,66353,66377.9209726444,66386.6946778711,66423.002739726,66424.3228699552,66437.4836065574,66440.7642276423,66450.2033898305,66541.3755274262,66552.2166666667,66553.9833795014,66601.4344262295,66619.6326530612,66711.3008130081,66712.1707317073,66718.955801105,66728.4326530612,66742.8571428571,66746.1140684411,66781.6585365854,66816.7786885246,66871.5847457627,66881.4222222222,66885.6797583081,66924.5403899721,66946.9915966386,66947.4895104895,66967.1721311475,66989.6405797101,67081.9673469388,67097.4943181818,67118.6723163842,67132.8617886179,67157.2282157676,67168.7723577236,67183.5690607735,67184.5387755102,67204.3844011142,67204.7020408163,67218.8258426966,67222.0687679083,67237.970845481,67259.0041493776,67305.4491525424,67363.602484472,67407.4552845528,67409.7724550898,67457.1056910569,67457.2711864407,67469.251396648,67503.3577235772,67551.0580645161,67557.5901639344,67567.9502762431,67595.0858725762,67596.8547486033,67608.0821917808,67637.4780058651,67646.9674796748,67672.3404255319,67677.4849785408,67685.1181556196,67693.3882352941,67696.7897727273,67740.4034582132,67763.041322314,67796.2857142857,67818.8505747126,67884.7008547009,67899.1814345991,67899.5447154471,67912.7901234568,67924.3452054794,67926.3127572016,67939.0165289256,67969.9175824176,67980.7479674797,67983.2931034483,67997.6593406593,68019.9674796748,68093.5983606557,68094.8926553672,68112.8126801153,68118.5327868852,68127.8563535912,68129.0204081633,68172.1111111111,68207.2427983539,68235.014084507,68237.243902439,68240.6554054054,68265.3860182371,68273.0348837209,68275.8012684989,68316.9461756374,68318.8418079096,68329.8847736625,68330.8664688427,68375.4277456647,68402.1959183673,68413.6916666667,68455.9090909091,68459.3086419753,68460.8991596639,68470.2049180328,68541.2923976608,68555.5944444444,68561.3974895398,68572.8524590164,68591.7283950617,68599.4146341463,68620.185915493,68631.7871148459,68674.2155172414,68735.9779005525,68813.7695473251,68814.7162790698,68834.9113924051,68845.7520661157,68881.3008130081,68888.132780083,68920.8797653959,68926.7877094972,68978.495412844,68988.2598870056,68996.3901098901,69001.1520467836,69030.6260162602,69054.4938271605,69054.5610859728,69098.9582172702,69157.5743440233,69161.4243070362,69179.3217391304,69216.6008230453,69231.0569105691,69233.1104651163,69252.3333333333,69306.4959349593,69365.0205479452,69367.375,69427.0909090909,69490.7845303867,69495.9905660377,69508.867768595,69521.8369905956,69540.8617886179,69545.6341463415,69556.6044776119,69556.8409090909,69571.2044817927,69578.0338983051,69581.0612244898,69586.4552845528,69601.0448979592,69666.4063492063,69715.1101694915,69717.7759103641,69725.5457063712,69726.5828571429,69748.8,69786.3510204082,69791.904494382,69829.0632183908,69833.1977715877,69864.5355648536,69899.5989010989,69924.5020920502,69945.5040650406,69946.6165413534,69951.8953168044,69963.8761061947,69985.1855955679,69986.868852459,69990.0689655172,70052.3434343434,70153.3091922006,70173.3352941177,70173.6081632653,70223.6509695291,70238.6956521739,70248.297752809,70270.2445414847,70306.4715447154,70399.9835390946,70425.3443526171,70437.8260869565,70478.4117647059,70491.9137931034,70509.7270194986,70512.3324099723,70572.8487394958,70585.1056910569,70620.461971831,70639.631147541,70652.081300813,70677.8337950138,70709.7016574586,70715.8487394958,70734.6684931507,70746.9826589595,70751.3801169591,70760.1377410468,70769.325203252,70772.8764044944,70781.9175824176,70782.6028169014,70824.590021692,70829.6080691643,70928.1422764228,70936.7670454545,70983.6232686981,71009.2990353698,71016.9105691057,71046.2967032967,71069.9510204082,71080.9158878505,71119.5914893617,71126.679558011,71149.7642276423,71169.2087912088,71210.4362606232,71219.547826087,71234.8271954674,71258.8222222222,71275.4775510204,71317.0581717451,71343.296398892,71359.6341463415,71370.3021978022,71373.0279329609,71408.3742690058,71433.9512195122,71439.6211699164,71451.2396694215,71473.7444444444,71483.3860465116,71510.0386740331,71546.3285302594,71562.2793296089,71588.9959183673,71597.621399177,71597.6703296703,71608.4056603773,71633.6308539945,71671.6997167139,71673.2098765432,71684.3423423423,71701.4333333333,71733.0622406639,71742.6481481481,71813.7402597403,71848.3774647887,71988.4065934066,72030.2717622081,72034.8130081301,72078.0941828255,72098.186440678,72130.8487084871,72219.8448753463,72229.9277777778,72243.5041322314,72258.9972451791,72280.5020576132,72283.5627906977,72320.8278688525,72340.9289617486,72346.870523416,72362.4550561798,72408.7068273092,72417.679558011,72419.487804878,72426.1828254847,72619.4448979592,72734.4894514768,72793.6759776536,72801.0975609756,72842.2040816326,72897.5609756098,72939.4450549451,72961.3608815427,72991.1586715867,73014.4734693878,73019.7419354839,73030.2045454545,73083.8622754491,73167.294117647,73199.2131147541,73272.3735632184,73299.8968481375,73301.9215686274,73392.3026584867,73579.9835164835,73617.5519125683,73671.9836734694,73746.9552238806,73760.3111111111,73785.182320442,73812.0991735537,73814.687150838,73818.9355742297,73932.5295774648,73959.402739726,74109.2786885246,74174.9711934156,74230.0936639118,74256.5613305613,74280.1277777778,74287.7692307692,74396.7811634349,74467.7,74531.3469387755,74641.1419354839,74728.8833922262,74735.9889807163,74752.8866995074,74786.3591836735,74801.6056338028,74809.9446640316,74893.3313953488,75034.2127659574,75064.9387755102,75071.1538461538,75159.864978903,75213.2887537994,75285.5542857143,75319.652892562,75376.9669421487,75406.4367346939,75429.1955922865,75435.9484240688,75450.1900826446,75457.2486187845,75536.4692082111,75642.9359331476,75686.9716088328,75768.864265928,75776.4848484848,75892.5393258427,75929.7307692308,75944.4179104478,76091.7127071823,76217.6978851964,76289.0809399478,76526.8605341246,76533.5376044568,76573.7851239669,76728.9392265193,76803.5524861878,76924.6790697674,76981.5540983606,76994.9398907104,77076,77102.7590027701,77109.5769230769,77185.456043956,77223.754601227,77227.1591836735,77236.9777777778,77344.098630137,77411.5512465374,77440.9944444444,77504.2105263158,77587.6086956522,77672.9971988795,77673.7434210526,77778.3581081081,77800.5082872928,77824.9150684932,77844.1052631579,77846.6741573034,78078.1538461538,78084.5942857143,78085.3994490358,78112.9230769231,78172.7342465753,78251.5934065934,78252.4786324786,78374.6765578635,78434.4493150685,78493.6978021978,78504.8066298342,78565.4630136986,78575.2947658402,78639.0304709141,78835.532967033,79003.0309859155,79017.2596685083,79132.6868131868,79159.2152588556,79207.860724234,79229.6134453781,79346.3209876543,79385.037037037,79389.5397260274,79506.2727272727,79512.602739726,79535.0714285714,79537.6558441558,79768.3085399449,79903.2658959538,79926.7507163324,79956.9808219178,79961.9323943662,80323.9890410959,80469.6923076923,80542.0989010989,80729.7967032967,80940.5545722714,80959.8469945355,81015.1342465753,81020.2521008403,81039.5780821918,81124.6590909091,81249.7517241379,81406.9433962264,81448.0109589041,81519.0092307692,81605.1726027397,81682.0443213296,81805.3223140496,81820.4552845528,81844.9534246575,81965.3650793651,82147.3150684932,82304.8486646884,82517.6932153392,82657.5258855586,82710.6666666667,82761.9917012448,82916.0386740331,82948.2762430939,82985.923566879,83416.1923076923,83546.5238095238,83687.1452054794,83721.1367521368,83754.7002967359,83816,83973.3036211699,84173.2657534247,84246.2684931507,84474.5056179775,84538.4547945205,84724.4958677686,84824.3736263736,84910.2307692308,84955.226519337,85380.202739726,85399.0591549296,85516.6904109589,85537.6712328767,85606,85681.6398891967,85819.7110481586,85844.9230769231,85856.0391061453,86122.7726027397,86536.0404624277,86691.4575342466,86706.0747663551,86744.0091743119,86755.5311004785,87021.8042813456,87068.2950819672,87327.2219178082,87827.3988764045,87906.8033707865,87998.8296703297,88081.591160221,88120.8472222222,88177.298630137,88188.898630137,88309.8082191781,88390.0621468927,88460.3212121212,88785.4515235457,88857.1123287671,89376.3123287671,89911.402173913,90191.8131868132,90724.1970149254,91112.3626373626,91135.4608695652,91250.8771929825,91251.9693165969,91479.0764872521,92474.1917808219,93596.0550964187,93793.1102661597,93807.901369863,94177.2375,95079.6153846154,95455.2256267409,97773.6220930233,99135.3663911846,99443.6219178082,99470.4444444444,99935.0049751244,100000.703225806,100728,101120.734246575,102603.125581395,103474.358208955,103736.61038961,103904.451790634,104865.072580645,105734.931034483],null,null,{"interactive":true,"className":"","stroke":false,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":["#FFFFCC","#FFF0A7","#FFEFA5","#FFEEA1","#FFEC9F","#FFEA9A","#FFEA9A","#FFE998","#FFE998","#FFE896","#FFE896","#FFE691","#FFE590","#FFE58F","#FFE48E","#FFE48D","#FFE38C","#FFE38C","#FFE38B","#FFE38A","#FFE28A","#FFE187","#FFE186","#FFE086","#FFE085","#FFE084","#FFE084","#FFDF83","#FFDF83","#FFDF83","#FFDF82","#FFDE81","#FFDE81","#FFDE81","#FEDD7E","#FEDD7E","#FEDD7E","#FEDC7D","#FEDC7D","#FEDC7D","#FEDC7C","#FEDC7B","#FEDB7B","#FEDB7A","#FEDB7A","#FEDB79","#FEDB79","#FEDA79","#FEDA79","#FEDA78","#FEDA78","#FEDA78","#FEDA78","#FEDA78","#FEDA77","#FEDA77","#FEDA77","#FED976","#FED976","#FED976","#FED976","#FED976","#FED875","#FED875","#FED875","#FED875","#FED874","#FED774","#FED774","#FED774","#FED774","#FED774","#FED773","#FED673","#FED673","#FED673","#FED673","#FED572","#FED572","#FED572","#FED572","#FED572","#FED571","#FED571","#FED471","#FED470","#FED470","#FED470","#FED470","#FED470","#FED370","#FED370","#FED36F","#FED26F","#FED26F","#FED26F","#FED26E","#FED26E","#FED16E","#FED16E","#FED16E","#FED16E","#FED16D","#FED16D","#FED16D","#FED16D","#FED16D","#FED16D","#FED06D","#FED06C","#FED06C","#FED06C","#FED06C","#FED06C","#FED06C","#FED06C","#FECF6B","#FECF6B","#FECF6B","#FFCF6B","#FFCF6B","#FFCE6B","#FFCE6B","#FFCE6B","#FFCE6A","#FFCE6A","#FFCE6A","#FFCE6A","#FFCE6A","#FFCE6A","#FFCD6A","#FFCD69","#FFCD69","#FFCD69","#FFCD69","#FFCD69","#FFCD69","#FFCD69","#FFCD69","#FFCC68","#FFCC68","#FFCC68","#FFCC68","#FFCC68","#FFCC68","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB67","#FFCB66","#FFCA66","#FFCA66","#FFCA66","#FFCA66","#FFCA66","#FFCA66","#FFCA66","#FFCA66","#FFCA65","#FFC965","#FFC965","#FFC965","#FFC965","#FFC965","#FFC965","#FFC965","#FFC965","#FFC965","#FFC965","#FFC964","#FFC964","#FFC864","#FFC864","#FFC864","#FFC864","#FFC864","#FFC864","#FFC863","#FFC863","#FFC863","#FFC863","#FFC763","#FFC763","#FFC763","#FFC662","#FFC662","#FFC662","#FFC662","#FFC661","#FFC561","#FFC561","#FFC561","#FFC561","#FFC561","#FFC561","#FFC561","#FFC560","#FFC560","#FFC560","#FFC460","#FFC460","#FFC460","#FFC460","#FFC45F","#FFC45F","#FFC45F","#FFC35F","#FFC35F","#FFC35F","#FFC35F","#FFC35F","#FFC35F","#FFC35E","#FFC35E","#FFC35E","#FFC25E","#FFC25E","#FFC25D","#FFC25D","#FFC25D","#FFC25D","#FFC25D","#FFC25D","#FFC25D","#FFC25D","#FFC25D","#FFC15D","#FFC15C","#FFC15C","#FFC15C","#FFC15C","#FFC15C","#FFC05C","#FFC05C","#FFC05C","#FFC05C","#FFC05B","#FFC05B","#FFC05B","#FFC05B","#FFC05B","#FFC05B","#FFC05B","#FFBF5B","#FFBF5A","#FFBF5A","#FFBF5A","#FFBF5A","#FFBF5A","#FFBF5A","#FFBF5A","#FFBF5A","#FFBF5A","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBE59","#FFBD58","#FFBD58","#FFBD58","#FFBD58","#FFBD58","#FFBD58","#FFBD58","#FFBD58","#FEBD58","#FEBD58","#FEBD58","#FEBD58","#FEBD57","#FEBC57","#FEBC57","#FEBC57","#FEBC57","#FEBC57","#FEBC57","#FEBC57","#FEBC57","#FEBC57","#FEBC56","#FEBC56","#FEBC56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB56","#FEBB55","#FEBB55","#FEBB55","#FEBB55","#FEBA55","#FEBA55","#FEBA55","#FEBA55","#FEBA54","#FEBA54","#FEBA54","#FEBA54","#FEBA54","#FEBA54","#FEB954","#FEB954","#FEB954","#FEB954","#FEB954","#FEB953","#FEB953","#FEB953","#FEB953","#FEB953","#FEB953","#FEB953","#FEB953","#FEB853","#FEB853","#FEB853","#FEB853","#FEB853","#FEB853","#FEB853","#FEB853","#FEB852","#FEB852","#FEB852","#FEB852","#FEB852","#FEB852","#FEB852","#FEB852","#FEB752","#FEB752","#FEB752","#FEB752","#FEB752","#FEB752","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB751","#FEB651","#FEB651","#FEB651","#FEB651","#FEB651","#FEB651","#FEB651","#FEB651","#FEB650","#FEB650","#FEB650","#FEB650","#FEB550","#FEB550","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB54F","#FEB44F","#FEB44F","#FEB44F","#FEB44F","#FEB44F","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB44E","#FEB34E","#FEB34E","#FEB34E","#FEB34D","#FEB34D","#FEB34D","#FEB34D","#FEB34D","#FEB34D","#FEB24D","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB24C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14C","#FEB14B","#FEB14B","#FEB14B","#FEB04B","#FEB04B","#FEB04B","#FEB04B","#FEB04B","#FEB04B","#FEB04B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4B","#FEAF4A","#FEAF4A","#FEAF4A","#FEAF4A","#FEAF4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAE4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAD4A","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAC49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAB49","#FEAA49","#FEAA49","#FEAA49","#FEAA48","#FEAA48","#FEAA48","#FEAA48","#FEAA48","#FEAA48","#FEA948","#FEA948","#FEA948","#FEA948","#FEA948","#FEA948","#FEA948","#FEA948","#FEA948","#FEA848","#FEA848","#FEA848","#FEA848","#FEA847","#FEA847","#FEA847","#FEA847","#FEA847","#FEA847","#FEA747","#FEA747","#FEA747","#FEA747","#FEA747","#FEA747","#FEA747","#FEA647","#FEA647","#FEA647","#FEA647","#FEA647","#FEA647","#FEA647","#FEA647","#FEA647","#FEA647","#FEA646","#FEA646","#FEA646","#FEA646","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA546","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA446","#FEA445","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA345","#FEA245","#FEA245","#FEA245","#FEA245","#FEA245","#FEA245","#FEA245","#FEA245","#FEA245","#FEA245","#FEA145","#FEA145","#FEA145","#FEA145","#FEA144","#FEA144","#FEA144","#FEA144","#FEA144","#FEA144","#FEA144","#FEA144","#FEA144","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FEA044","#FE9F44","#FE9F44","#FE9F44","#FE9F44","#FE9F44","#FE9F44","#FE9F44","#FE9F44","#FE9F44","#FE9F43","#FE9F43","#FE9F43","#FE9F43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9E43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D43","#FE9D42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9C42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9B42","#FE9A42","#FE9A42","#FE9A42","#FE9A42","#FE9A42","#FE9A42","#FE9A41","#FE9A41","#FE9A41","#FE9A41","#FE9A41","#FE9A41","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9941","#FE9841","#FE9841","#FE9841","#FE9841","#FE9841","#FE9841","#FE9841","#FE9840","#FE9840","#FE9740","#FE9740","#FE9740","#FE9740","#FE9740","#FE9740","#FE9740","#FE9740","#FD9740","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD9640","#FD953F","#FD953F","#FD953F","#FD953F","#FD953F","#FD953F","#FD953F","#FD953F","#FD953F","#FD953F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD943F","#FD933F","#FD933F","#FD933F","#FD933F","#FD933E","#FD933E","#FD933E","#FD933E","#FD933E","#FD933E","#FD933E","#FD933E","#FD933E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD923E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD913E","#FD903D","#FD903D","#FD903D","#FD903D","#FD903D","#FD903D","#FD903D","#FD903D","#FD903D","#FD903D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8F3D","#FD8E3D","#FD8E3D","#FD8E3D","#FD8E3C","#FD8E3C","#FD8E3C","#FD8E3C","#FD8E3C","#FD8E3C","#FD8E3C","#FD8D3C","#FD8D3C","#FD8D3C","#FD8D3C","#FD8D3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3C","#FD8C3B","#FD8B3B","#FD8B3B","#FD8B3B","#FD8B3B","#FD8B3B","#FD8B3B","#FD8A3B","#FD8A3B","#FD8A3B","#FD8A3B","#FD8A3B","#FD8A3B","#FD8A3B","#FD893B","#FD893B","#FD893B","#FD893B","#FD893B","#FD893B","#FD893B","#FD893B","#FD883A","#FD883A","#FD883A","#FD883A","#FD883A","#FD883A","#FD883A","#FD873A","#FD873A","#FD873A","#FD863A","#FD863A","#FD863A","#FD863A","#FD863A","#FD8639","#FD8639","#FD8539","#FD8539","#FD8539","#FD8539","#FD8539","#FD8539","#FD8539","#FD8539","#FD8539","#FD8539","#FD8439","#FD8439","#FD8439","#FD8439","#FD8439","#FD8439","#FD8339","#FD8339","#FD8339","#FD8339","#FD8339","#FD8338","#FD8338","#FD8338","#FD8238","#FD8238","#FD8238","#FD8238","#FD8238","#FD8238","#FD8238","#FD8138","#FD8138","#FD8138","#FD8138","#FD8138","#FD8138","#FD8138","#FD8038","#FD8038","#FD8038","#FD8038","#FD8038","#FD8038","#FD8038","#FD8037","#FD8037","#FD7F37","#FD7F37","#FD7F37","#FD7F37","#FD7F37","#FD7F37","#FD7F37","#FD7F37","#FD7F37","#FD7E37","#FD7E37","#FD7E37","#FD7E37","#FD7D37","#FD7D36","#FD7D36","#FD7C36","#FD7C36","#FD7C36","#FD7B36","#FD7B36","#FD7B36","#FD7B36","#FD7B36","#FD7B36","#FD7B36","#FD7B36","#FD7B36","#FD7A36","#FD7A36","#FD7A36","#FD7A36","#FD7A36","#FD7935","#FD7835","#FD7835","#FD7835","#FD7735","#FD7735","#FD7735","#FD7735","#FD7635","#FD7634","#FD7634","#FD7634","#FD7634","#FD7534","#FD7534","#FD7534","#FD7434","#FD7434","#FD7434","#FD7233","#FD7233","#FD7233","#FD7133","#FD7133","#FD7133","#FD7133","#FD7133","#FD7133","#FD7033","#FD7033","#FD6F32","#FD6E32","#FD6E32","#FD6E32","#FD6E32","#FD6E32","#FD6D32","#FD6C32","#FD6C31","#FD6B31","#FD6B31","#FD6B31","#FD6B31","#FD6A31","#FD6A31","#FD6A31","#FD6A31","#FD6930","#FD6830","#FD6830","#FD6830","#FD6730","#FD6730","#FD6730","#FD6630","#FD6630","#FD6630","#FD6630","#FD6630","#FD6630","#FD652F","#FD642F","#FD642F","#FD632F","#FD632F","#FD622F","#FD622F","#FD622F","#FD612E","#FD602E","#FD5F2E","#FD5E2E","#FD5E2E","#FD5D2D","#FD5C2D","#FD5C2D","#FC5B2D","#FC5A2D","#FC5A2D","#FC592D","#FC592C","#FC592C","#FC592C","#FC582C","#FC582C","#FC582C","#FC572C","#FC572C","#FC562C","#FC562C","#FC552C","#FC552B","#FC552B","#FC542B","#FC542B","#FC532B","#FC532B","#FC532B","#FC512B","#FC512B","#FC512B","#FC512B","#FC502B","#FC502A","#FC502A","#FC4F2A","#FC4E2A","#FC4E2A","#FC4E2A","#FC4D2A","#FC4D2A","#FB4D2A","#FB4C29","#FA4C29","#FA4B29","#FA4B29","#FA4B29","#FA4B29","#FA4B29","#FA4A29","#F94A29","#F94A29","#F94928","#F94928","#F94928","#F94928","#F84828","#F84728","#F84728","#F84728","#F84728","#F74527","#F64527","#F64427","#F64426","#F54326","#F54226","#F54226","#F54226","#F54226","#F54226","#F44126","#F44025","#F44025","#F44025","#F33F25","#F33F25","#F33E25","#F33E25","#F33E25","#F23D24","#F23D24","#F13C24","#F13B24","#F03A23","#F03A23","#F03923","#F03923","#F03823","#F03823","#EE3622","#EE3522","#EE3422","#EE3422","#ED3422","#ED3422","#ED3321","#EC3221","#EC3121","#EB3021","#EB3020","#EB2E20","#EB2E20","#EA2D20","#EA2D20","#E92A1F","#E92A1F","#E9291F","#E9291F","#E8291F","#E8281F","#E8271F","#E8271F","#E8271F","#E7251E","#E6221D","#E5211D","#E5211D","#E5211D","#E5211D","#E41F1D","#E41E1D","#E41C1C","#E2191C","#E1191D","#E1191D","#E1191D","#E1191D","#E0191D","#E0181D","#E0181D","#DF181D","#DF181D","#DE171E","#DD171E","#DB161F","#D9141F","#D81320","#D61220","#D41121","#D41121","#D31121","#D31121","#D21021","#CE0D22","#CA0923","#C90923","#C90923","#C70724","#C30525","#C20325","#B50026","#AC0026","#AA0026","#AA0026","#A60026","#A60026","#A10026","#9E0026","#950026","#8F0026","#8D0026","#8C0026","#860026","#800026"],"fillOpacity":0.6},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]},{"method":"addLegend","args":[{"colors":["#FFFFCC , #FFF1AA 9.64491747564047%, #FEDC7B 23.390285593082%, #FEB34D 37.1356537105235%, #FD893B 50.881021827965%, #F84728 64.6263899454065%, #D9141F 78.371758062848%, #A60026 92.1171261802895%, #800026 "],"labels":["0 - 2.500000e-02","0 - 3.000000e-02","0 - 3.500000e-02","0 - 4.000000e-02","0 - 4.500000e-02","0 - 5.000000e-02"],"na_color":null,"na_label":"NA","opacity":1,"position":"bottomright","type":"numeric","title":"Avg. Daily O3 (ppb)","extra":{"p_1":0.0964491747564046,"p_n":0.921171261802895},"layerId":null,"className":"info legend","group":null}]}],"limits":{"lat":[18.177939,48.95074],"lng":[-124.62491,-65.915482]}},"evals":[],"jsHooks":[]}</script><!--/html_preserve-->
We can see that there are many more sensors for Ozone than Nitorus Dioxide. The areas of the country with the worst levels of Ozone are California, Arizona, Utah, Colorado, and Wyoming. For the most part, levels on the East coast and midwest are not as high.

Finally, let's take a look at AQI.


```r
#--> Color spectrum
Npal3 <- colorNumeric(
  palette = "YlOrRd", n = 10,
  domain = daily_mean_o3_sf$DailyMeanAQI
)

#--> Make our map
aqi_circles_map <- daily_mean_o3_sf %>%
  leaflet() %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
  addCircles(radius = daily_mean_o3_sf$DailyMeanPPB*2000000, fillOpacity = .6, 
             fillColor = Npal3(daily_mean_o3_sf$DailyMeanAQI), stroke = FALSE) %>%
  addLegend("bottomright", pal = Npal3, values = ~DailyMeanAQI, 
            labFormat = function(type, cuts, p) {
              n = length(cuts) 
              paste0(prettyNum(cuts[-n], digits=0, big.mark = ",", scientific=F), 
                     " - ", prettyNum(cuts[-1], digits=0, big.mark=",", scientific=T))},
            title = "Avg. Daily Air Quality Index", opacity = 1)

aqi_circles_map
```

<!--html_preserve--><div id="htmlwidget-301b1ef3582161607c11" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-301b1ef3582161607c11">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["Stamen.TonerLines",null,"Basemap",{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addProviderTiles","args":["Stamen.TonerLite",null,"Basemap",{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[18.440774,37.362137,37.864767,41.726892,34.325318,32.362606,18.420089,35.4884,29.758889,48.52059,40.92458,40.776944,32.538364,37.814781,45.393497,29.828086,29.625556,38.8795,38.895572,29.99497,38.403765,33.089772,41.442778,33.213611,48.95074,37.743065,34.474526,43.8345,33.81468,33.6878,42.385998,37.4826,37.765946,47.568236,44.965242,37.97231,29.767997,25.892518,30.439722,37.482934,33.545278,41.965193,32.364565,30.085263,37.9604,40.008889,32.668987,39.787933,38.548136,38.310942,40.720989,30.681718,29.686389,30.419805,31.188933,33.553056,35.0608,38.62901,29.834167,38.346258,43.660246,29.802707,26.22621,34.1795,33.331111,30.057515,30.204051,30.700895,34.949147,47.5525,44.026312,40.67025,30.227798,30.848611,37.28329,34.851537,47.49022,30.315406,45.496641,29.764098,40.043833,30.1103,40.816,30.036422,30.429381,33.3169,30.770181,33.612406,32.329111,33.578333,33.8025,30.229653,41.705226,29.489083,29.733726,34.402773,36.983921,33.485556,38.102507,40.81976,41.265556,26.200335,30.477725,28.45445,35.498711,43.68578,42.605816,34.762619,30.7017,26.053889,27.939746,29.623889,30.178056,30.201111,43.629605,33.386389,42.930521,40.51408,30.378217,37.687526,37.348497,32.805264,29.863957,30.500642,36.060833,38.612034,29.192754,44.155636,34.01194,39.101439,43.608056,40.692224,30.461981,44.80353,38.23887,33.40405,27.350278,46.933754,41.52375,29.670025,32.509959,29.566112,35.434767,29.901036,36.495767,36.69676,40.747796,27.517449,37.950741,34.364167,33.4339,40.272222,33.582044,41.479116,40.8679,26.073536,40.246992,33.007866,34.9127,40.36644,30.140265,26.270083,39.14566,38.508075,46.952562,32.346722,33.588545,42.718653,42.3295,29.043759,39.01893,32.987252,34.63782,42.386811,25.587327,40.283092,29.170533,40.535278,40.309722,40.146667,34.756189,43.9731,41.855243,27.449763,40.452913,43.944519,27.633089,45.768531,29.695729,35.721095,30.4747,27.089194,38.650783,26.088421,35.40814,36.209286,40.277647,28.332225,43.974622,40.515262,45.168004,45.616667,28.347509,48.5103,29.723333,41.492117,41.3014,31.954286,29.9425,27.832409,33.9039,28.090299,36.205055,32.68336,34.002747,38.45934,29.978926,38.53445,37.04926,38.558228,40.628056,34.44551,39.055277,40.38335,30.260278,42.22862,38.47753,36.804669,27.928356,41.784722,46.81826,40.73614,39.28102,38.013333,28.83617,28.028889,34.264917,30.039524,31.6675,35.96522,46.493633,40.995848,29.897516,44.81029,32.06848,37.743649,45.13768,38.194501,33.433949,39.422273,46.713694,43.656764,29.109151,41.530011,34.06659,39.965278,26.593808,29.939614,41.606667,39.810833,29.823319,41.2508,37.98629,35.197288,33.8005,39.991389,37.936013,32.412811,38.970092,34.530717,41.78555,40.304694,39.263914,40.462182,42.099699,27.172458,34.093959,30.221255,27.189215,35.49453,29.520443,36.46983,40.046667,36.60843,37.226862,35.50716,35.972347,47.948622,42.62668,38.654069,48.15278,46.602248,47.3132,39.024265,46.842181,38.47367,42.334982,39.0905,34.06703,41.096188,43.2185,42.770837,30.041238,44.377794,41.05192,29.275381,37.62668,39.21487,33.901389,37.35748,35.603056,36.844096,38.613779,38.302591,36.999571,33.4124,27.96565,30.426533,35.217501,31.169805,28.596389,40.107222,38.91833,39.448105,27.76534,29.583047,40.814183,36.922222,38.006311,34.376227,45.40184,27.785866,33.92513,39.138773,44.308132,28.053611,42.065106,33.9632,39.739444,36.29756,39.117219,34.751848,40.244913,32.378682,42.984173,41.45589,35.590833,44.791437,40.611944,39.0327,33.153088,37.55652,40.712778,40.337328,36.011703,40.170556,43.44957,41.08306,40.46542,45.549839,43.05235,27.946688,38.22876,41.849433,39.83562,29.632058,36.085508,44.7614,46.6041,32.941023,30.0925,32.466389,32.631231,39.0284,43.060975,39.835556,35.500102,34.285696,26.292025,41.615237,30.22611,40.811389,40.870436,36.150799,38.48123,39.533761,36.8071,30.088872,36.204902,32.676451,34.977,40.549985,30.300833,48.397787,33.83062,30.350302,45.402446,40.518735,38.339905,47.940861,41.18208,35.36631,37.702066,39.323533,32.46735,35.2401,37.09798,39.934446,34.772727,33.739963,37.079379,32.656357,34.52744,41.247486,33.746056,40.114876,34.427775,27.480873,34.605819,39.310833,32.536273,41.7514,41.603159,34.623236,33.0325,35.158686,40.82799,29.51509,39.327391,39.9878,38.838575,39.838119,36.66525,27.389079,28.523889,34.015436,42.88759,38.06091,41.322508,36.032955,37.1655,40.445278,43.58889,35.551868,32.820061,39.773889,35.988333,28.195574,42.68075,39.85567,40.05278,43.996908,34.10002,26.548212,46.825425,37.60613,41.094965,39.5513,40.112222,38.448672,40.71528,43.28428,43.54792,42.049148,32.175417,37.908533,39.202935,35.856111,27.740033,41.97677,41.670992,30.497478,38.656429,38.860669,38.424133,34.252378,46.851811,40.57747,39.114313,26.449247,41.221537,39.54182,46.39674,29.206667,38.66121,38.20087,41.69666,40.74529,33.918137,44.348604,35.231459,28.746111,44.473754,37.954444,37.34438,43.075371,43.14618,40.68742,38.307913,32.521272,44.310555,44.4438,35.9138,38.393822,30.525367,39.485987,34.988706,40.356694,48.41252,32.805818,39.96523,41.454597,40.984723,41.207958,34.448048,35.85408,42.751518,39.800339,40.3125,38.227066,48.317507,35.256577,41.984332,34.653606,38.358365,42.19438,41.874999,35.81066,36.708607,31.746775,40.617488,43.343167,35.151699,31.785769,43.600699,41.644067,37.93829,34.885608,36.89117,34.1326,30.394133,38.770081,39.77949,46.288877,41.832256,41.677667,33.37005,42.467573,29.727931,42.221442,35.438556,39.575634,38.71209,41.66812,42.51334,44.230622,37.8712,42.99328,41.514727,44.963633,42.281013,40.026037,36.742227,36.0388,42.738618,39.460478,39.540917,38.07657,39.12886,34.82166,41.639444,41.361856,43.016667,47.1411,30.483168,30.390369,42.743036,42.139996,47.41645,43.123704,39.866834,39.831522,38.6539,32.936523,38.921847,36.133802,34.687761,34.8848,43.566122,33.720742,39.761538,41.699174,41.716959,39.469219,43.7775,42.09142,36.019186,38.869001,47.5812,40.076389,30.354436,44.18089,35.935833,46.2053,39.07807,33.57454,35.03146,32.172995,39.751184,44.08747,32.564968,42.798339,45.20916,39.749027,25.732878,43.01209,33.219069,41.6175,33.9508,43.6138,37.47689,43.22386,47.298611,48.29786,37.281598,37.654456,45.25928,38.986672,33.45793,43.466111,37.155392,48.64193,38.81194,27.307268,38.49011,39.6359,36.1797,39.529444,41.206321,27.892523,34.46245,38.7408,34.835721,36.141875,35.4325,32.442304,30.378287,33.503833,39.68425,38.85287,39.210857,33.342226,44.531907,32.38082,35.750735,37.487981,34.05111,41.629167,33.47968,41.645381,38.745726,32.98426,40.0877,32.344008,46.0519,39.169533,37.897506,44.735978,42.14175,42.278067,42.862531,30.130433,43.561043,36.58211,41.4271,42.474642,37.67696,41.399167,36.707727,41.182466,40.816038,41.118333,33.362593,36.634225,38.587525,40.00103,42.274319,43.020075,33.48385,41.841039,40.427372,37.780776,39.432117,45.2066,32.204411,37.05822,42.2869,41.377685,40.7208,43.278061,33.801667,37.205862,39.384671,39.42276,33.40316,38.494475,35.314158,32.508306,38.920835,35.378153,41.420882,38.051667,35.953708,31.765685,34.289001,35.641276,36.307033,43.917955,41.215014,37.28342,41.945874,31.653074,36.35586,43.23086,33.410648,37.705612,42.060285,34.974039,40.969112,42.240565,37.13179,39.817222,35.2632,39.66575,34.153,44.53098,44.30738,39.410191,31.930659,36.191251,32.919206,38.7791,35.111944,40.300385,37.641583,41.106486,43.168336,35.631629,42.463063,39.834461,32.031934,39.474976,45.602419,39.5327,42.814412,36.48324,41.813049,36.141111,37.256137,32.482083,44.138619,39.758889,35.01708,40.959604,43.047224,38.13784,42.416636,32.845467,41.4942,36.91171,40.06483,43.953334,41.551667,42.51831,39.961111,40.684722,41.84046,36.867125,36.228408,39.328807,39.86097,39.649367,32.987891,35.159649,42.953336,36.90118,39.396075,45.565,40.310025,32.29515,43.836388,40.787628,34.131262,28.310841,42.731394,36.541365,34.615367,35.233476,44.980577,36.026,40.540455,45.366151,43.0034,40.253611,33.741242,39.464872,36.233274,33.1787,30.36805,41.685707,37.89147,39.789486,41.512118,39.4125,40.59664,44.52839,32.676186,36.109167,35.949765,41.1175,37.350054,44.70735,38.77335,39.858889,33.447867,36.306965,39.42689,44.37705,38.8577,43.4351,47.185833,42.19779,39.785644,32.922474,39.80933,44.307,44.28,38.082155,32.952124,39.558525,35.614131,36.110693,33.945379,36.7841,35.503587,38.872546,40.17093,31.768291,40.068297,42.49963,41.598119,39.02473,38.176278,35.331302,41.221418,43.687402,39.305021,40.386368,40.689253,38.4002,41.754722,39.997732,37.2385,31.122419,34.54166,43.100838,42.4006,38.508547,43.045269,43.1818,36.105481,39.564178,43.176672,29.254474,32.868773,41.240453,42.829154,34.210154,44.39308,38.06503,34.63298,35.002304,36.158414,33.080087,38.8994,34.895007,39.2787,44.616943,33.995638,40.93133,40.695078,33.590833,43.815596,33.29898,36.953256,41.285533,38.113889,36.705506,41.780261,40.82812,38.885528,35.479215,33.1324,32.690278,40.08502,36.308889,41.0604,42.8608,45.2384,36.031831,34.725538,36.512368,42.894451,42.580009,31.088002,35.320105,39.9428,40.002511,35.299484,43.3156,39.444294,41.058617,34.404268,47.803392,38.444971,39.613367,38.00641,39.294322,39.92002,36.332179,39.78819,32.954361,36.956222,39.70595,39.021881,47.8679,38.115152,34.805261,41.004657,35.477036,43.4981,39.9231,41.644722,39.417243,37.103733,38.201852,41.995568,41.959695,32.579361,42.298493,37.7046,34.276362,41.842649,36.819111,34.8147,39.563333,37.9214,46.8943,35.477801,37.69,42.211774,37.319186,38.683304,37.682512,27.8492,35.102638,32.789561,40.770944,41.976389,43.343,33.508125,39.067159,33.217025,33.99958,39.100174,39.621434,33.488242,39.407452,40.56333,34.14435,42.767786,35.35472,35.1343,39.525083,36.05097,45.440295,37.13678,34.10374,41.552196,35.832726,39.472471,32.353595,42.5958,41.55523,33.78942,41.35362,32.317593,39.166017,38.985578,38.890186,34.1365,38.536722,46.2756,45.828968,40.56252,44.6522,39.303174,41.726811,33.56033,41.975804,40.96078,41.330469,36.841331,41.717762,33.63003,38.70608,41.49511,42.43084,39.602787,33.474609,36.314399,34.226639,37.360684,39.0828,38.958341,38.75961,44.44312,41.821342,41.673006,41.669001,41.91056,42.86183,34.38344,41.30283,39.701444,41.13069,37.689615,36.048705,36.785322,41.89557,36.106389,38.342743,35.23668,39.331913,32.726656,39.1447,39.430038,36.105629,32.04767,36.59745,33.54549,35.356601,39.399837,39.43806,44.146964,39.04577,41.755832,31.893913,38.71085,34.454514,31.87952,34.510014,33.67649,40.084555,41.492707,40.736389,33.41045,41.256788,39.915409,42.8463,42.504722,37.10258,40.745504,43.667418,43.670833,37.90084,33.63713,40.070016,41.537069,39.53063,39.9544,37.981582,33.290229,42.062053,33.67464,40.902967,34.10688,36.1058,38.935578,32.79222,39.645264,31.796218,44.351697,34.19925,40.136336,46.8505,36.809735,34.48974,38.726573,40.038889,32.380118,41.1525,40.375644,36.807913,35.206111,40.600532,36.16976,39.250409,39.110539,37.70264,33.880812,43.74561,33.45223,37.179125,34.596095,42.778304,37.3297,33.71881,41.303614,40.216779,40.294178,42.229891,33.61103,42.486361,41.158,36.270592,42.82231,47.048537,39.130575,34.785219,39.638781,35.61975,42.869824,34.2439,43.101281,38.5231,39.567887,32.425261,33.4214,39.534488,42.7907,33.507992,40.592543,35.25793,44.36608,39.254449,34.8803,46.7841,32.041212,35.63348,44.933611,40.53999,36.173415,36.985119,42.719,41.182227,29.30265,35.785665,40.086944,40.4372,43.460556,35.562872,36.796667,46.204582,40.483598,35.763873,47.82728,38.853097,40.46471,43.873056,39.541515,34.671394,43.55764,41.515051,41.750556,43.577603,41.386944,39.743724,44.270093,39.638522,43.081667,35.587144,35.346094,35.696758,38.81161,33.9397,32.1783,31.787885,35.379167,36.357786,32.00941,40.496392,40.206291,40.05671,40.329253,34.82251,41.373097,33.6547,36.187742,34.05977,37.30389,35.64368,32.174538,33.82169,37.1983,35.978149,36.48947,39.60996,35.438869,42.373499,44.56536,33.70853,38.890941,35.765413,35.524544,38.725282,39.912799,35.1852,38.9564,33.293465,39.00512,39.240278,36.035,33.92086,37.71325,33.583333,34.418073,34.612055,37.1984,39.714041,33.706328,36.39103,32.842242,38.45832,33.85275,42.529999,36.569333,40.27813,36.508611,36.05864,35.050551,32.725226,42.9288,35.05443,39.205572,34.2431,41.3642,33.944713,33.9828,34.426126,37.549928,39.794391,18.177939,39.234331,36.567178,40.262072,36.318874,34.06957,33.7411,35.1019],[-66.126531,-118.417478,-122.302741,-122.633579,-82.386376,-88.277992,-66.150615,-97.090278,-95.079444,-122.61428,-75.067815,-124.1775,-86.232347,-122.282347,-122.747894,-95.284096,-95.267222,-80.8477,-76.958072,-90.817415,-122.818294,-87.459733,-75.623056,-115.54528,-122.55441,-122.169935,-85.408847,-123.0353,-80.781135,-84.2905,-83.266189,-82.53532,-122.399044,-122.308628,-93.254759,-122.520004,-95.220582,-97.49383,-84.346389,-122.20337,-86.549167,-87.876265,-88.731491,-93.761341,-122.356811,-75.09778,-94.167457,-86.13088,-82.731163,-122.296189,-74.192892,-91.366247,-95.294722,-91.182016,-85.423094,-86.815,-83.4306,-82.45886,-95.489167,-81.621161,-70.268965,-95.125495,-98.291069,-93.0988,-87.003611,-90.619286,-91.117384,-91.056068,-120.43763,-122.064722,-123.083737,-74.126081,-93.579965,-85.603889,-83.20932,-82.744576,-121.77278,-90.811383,-122.602877,-90.765275,-76.1124,-84.9903,-73.902,-94.071061,-90.199678,-86.825,-88.087761,-114.602886,-90.182722,-86.773889,-118.22,-90.965628,-76.512726,-81.276833,-95.257593,-119.458454,-121.989328,-86.915,-122.237976,-73.94825,-75.846389,-97.712684,-81.587339,-81.381181,-83.310242,-74.98538,-72.596689,-87.638097,-94.6742,-80.256944,-82.000084,-95.474167,-82.619167,-82.441111,-72.309499,-86.816667,-72.272332,-75.789721,-81.8409,-121.784217,-121.894898,-83.543493,-94.317802,-91.213556,-86.286261,-90.160477,-82.173149,-103.315765,-118.06995,-90.344494,-72.982778,-75.237156,-91.179219,-106.961763,-82.9881,-84.745728,-82.479722,-96.85535,-74.21534,-95.128508,-92.046196,-82.26608,-83.442133,-95.326137,-121.731571,-121.637182,-80.316442,-99.515219,-121.268523,-77.838611,-82.0224,-76.681389,-82.131249,-75.578186,-73.87809,-80.33845,-76.846988,-80.965038,-80.8745,-80.61558,-93.368448,-81.710959,-123.20298,-82.659241,-122.59527,-90.225667,-84.069608,-71.522416,-71.0826,-95.472946,-122.91333,-79.9367,-120.4575,-83.270506,-80.325922,-74.742644,-82.100646,-78.370833,-78.915,-79.902222,-92.281296,-74.2232,-87.75247,-82.522041,-122.298866,-71.700788,-82.54593,-122.7721,-95.499219,-84.343035,-88.1411,-82.362583,-121.506767,-80.111193,-94.524413,-121.126371,-74.0051,-82.305643,-70.124608,-74.806671,-92.765136,-122.516667,-81.636464,-113.99681,-95.635833,-81.678449,-72.902871,-84.08101,-94.000556,-97.55538,-86.0539,-82.700707,-86.74472,-93.861582,-89.799183,-82.64041,-94.010872,-121.7734,-86.21487,-121.492981,-75.341111,-119.8284,-76.878333,-75.9686,-81.453611,-83.2082,-78.81952,-94.725024,-82.454539,-72.631667,-92.08936,-73.82153,-78.08157,-87.577222,-97.00553,-81.972222,-88.766222,-95.673951,-106.288,-84.22316,-84.364207,-80.346442,-93.991084,-122.915085,-81.04942,-121.934188,-93.207615,-87.341396,-84.161811,-75.025204,-92.511722,-70.629138,-80.993666,-90.587611,-118.22688,-76.699444,-80.058492,-89.923883,-87.304722,-86.114444,-94.983786,-76.9238,-85.71192,-90.193141,-78.9941,-75.080833,-122.026154,-86.263394,-77.016715,-86.967536,-73.74136,-79.505667,-86.292269,-74.429439,-71.619399,-80.240689,-80.962304,-91.315418,-81.34035,-120.66617,-95.392509,-83.826511,-76.283333,-83.73694,-121.979675,-82.96337,-81.933072,-91.495574,-71.362068,-122.901857,-103.63951,-90.656141,-102.5273,-95.711275,-114.021499,-77.76772,-89.037775,-79.6617,-117.7514,-80.658867,-71.5145,-71.10229,-90.272826,-70.854697,-73.76366,-98.311692,-79.51257,-84.69086,-118.205,-77.59355,-83.783611,-121.362121,-121.368014,-121.420838,-121.574684,-111.93473,-82.2304,-86.666217,-90.019707,-81.495035,-81.3625,-74.882222,-84.852637,-77.963845,-97.434262,-95.015544,-79.56475,-94.838889,-121.641918,-84.059506,-93.20306,-82.739875,-117.95264,-121.618549,-71.217639,-80.628611,-71.012129,-84.0691,-75.558056,-86.653137,-94.635605,-82.256701,-88.188519,-94.711811,-85.671339,-73.70977,-78.461944,-93.512534,-75.4325,-122.92229,-96.115572,-77.40027,-81.598333,-76.383447,-94.167436,-80.261389,-74.51625,-75.32328,-79.960757,-94.13345,-76.05921,-82.731767,-85.65452,-93.697617,-84.720524,-98.564936,-83.764806,-91.143,-68.4135,-79.657187,-84.161111,-114.768611,-117.059075,-76.8171,-87.913504,-75.3725,-82.59986,-79.744859,-80.09647,-71.72,-92.042908,-77.877028,-73.991994,-86.623297,-77.3704,-122.191903,-108.69523,-91.869595,-95.976537,-96.87206,-81.207,-122.382011,-89.395916,-122.504971,-117.93845,-95.425128,-122.854437,-88.996896,-120.763515,-101.571583,-74.02819,-120.84271,-97.314847,-81.552367,-85.083447,-80.785683,-84.61152,-75.125291,-86.756174,-81.853635,-121.600031,-97.088585,-120.1965,-95.973142,-90.723028,-80.700972,-119.691218,-82.618709,-120.075069,-76.474444,-93.74894,-87.713488,-93.643118,-82.532059,-115.62361,-78.728035,-73.05754,-98.620166,-94.95102,-79.2515,-94.746424,-104.94984,-76.73078,-80.311033,-81.723333,-84.607423,-73.24984,-85.89804,-95.938593,-78.904037,-78.3069,-80.420833,-70.87734,-80.395039,-96.860117,-75.496389,-77.582778,-82.756264,-73.75733,-83.99773,-88.37251,-92.450366,-117.49201,-81.981523,-100.76821,-77.2188,-85.101816,-75.732,-75.309167,-90.395904,-124.20139,-76.46324,-96.700769,-88.273029,-96.870189,-80.632633,-122.017728,-78.574167,-82.465146,-91.68766,-87.732457,-87.880258,-90.198348,-90.105851,-82.4259,-119.143176,-95.846272,-105.07892,-77.106876,-81.939256,-88.190967,-107.784125,-94.1303,-81.0525,-121.73269,-77.37742,-86.214722,-73.41919,-83.344385,-96.807299,-77.568792,-81.310556,-93.012611,-87.321667,-77.25925,-70.748017,-77.54817,-89.606943,-85.834313,-84.944635,-84.891865,-95.81789,-81.191,-85.664118,-87.20355,-87.401312,-82.075802,-83.063971,-92.829225,-97.356568,-82.95549,-80.589612,-96.677513,-95.945897,-119.231321,-94.985964,-96.707208,-75.212119,-74.8729,-122.075624,-107.862471,-120.669861,-87.792002,-82.838659,-121.950003,-72.555112,-90.177574,-76.906249,-86.566284,-106.402806,-79.727664,-70.471034,-89.850249,-106.323578,-116.347853,-83.54616,-86.89719,-95.78441,-81.25423,-118.1272,-87.008033,-99.763424,-105.00518,-85.950227,-95.928185,-108.024835,-112.6207,-87.810047,-93.894081,-88.242207,-81.27675,-86.477893,-121.38109,-87.99057,-83.005971,-69.785,-87.46375,-78.77153,-90.51735,-67.060728,-91.526879,-82.432996,-107.977567,-85.7331,-84.534633,-76.633543,-119.746761,-78.50397,-84.50404,-89.98783,-87.493611,-81.86463,-87.933333,-121.9379,-97.872301,-89.049778,-92.513241,-87.799227,-117.52997,-94.693518,-88.925594,-89.640926,-75.6106,-96.459211,-77.013178,-95.764537,-86.586362,-76.6203,-71.496335,-84.357316,-121.84162,-90.521944,-85.824696,-119.775354,-91.2269,-77.20978,-83.87381,-89.622816,-103.2995,-75.011944,-97.760255,-85.738985,-81.530278,-93.75945,-92.31626,-112.19196,-120.50103,-110.980134,-104.987625,-75.97316,-96.317687,-84.393795,-93.66921,-86.186269,-80.16175,-73.6489,-97.196284,-87.199167,-118.43043,-83.3591,-97.366399,-78.47888,-101.766944,-124.62491,-120.434992,-122.031547,-122.588151,-75.5568,-112.04601,-88.621111,-88.394024,-102.4018,-76.74417,-82.570376,-90.70509,-83.2605,-94.116827,-84.393453,-111.975524,-82.538429,-120.02551,-87.4853,-92.260581,-115.078742,-79.2887,-97.803529,-88.53393,-112.095767,-74.861491,-77.63462,-87.668297,-81.788731,-67.59587,-111.12716,-94.669697,-120.837005,-118.45636,-86.684444,-111.91721,-70.897504,-121.266312,-97.063721,-82.959773,-95.415752,-89.654,-76.627933,-97.492083,-68.670752,-80.038611,-85.54189,-71.38014,-85.731517,-70.207324,-82.485742,-80.1451,-70.970816,-95.47594,-73.443056,-93.222,-81.330486,-85.661408,-73.336667,-117.09023,-120.382331,-76.141006,-83.80456,-71.875511,-88.21507,-112.14257,-71.36097,-80.592318,-87.075307,-81.460443,-90.5969,-110.878067,-88.57251,-89.9997,-83.611104,-77.9319,-86.311083,-86.9425,-107.254118,-84.540537,-77.37519,-112.07533,-121.211131,-80.713469,-111.308056,-86.080523,-89.83447,-82.095729,-87.278056,-96.004975,-106.455227,-85.970065,-77.360126,-79.467417,-69.26059,-80.484779,-79.88452,-112.233973,-97.070698,-96.01243,-77.17136,-96.94459,-85.852629,-87.863225,-80.540622,-95.044951,-83.599602,-86.142953,-75.563889,-79.8365,-83.94268,-95.3213,-87.90799,-88.395178,-76.296946,-106.631103,-115.122953,-96.808498,-75.16323,-98.252778,-85.245862,-120.994622,-81.503547,-83.461541,-120.690977,-83.183199,-75.768242,-96.399141,-91.788991,-121.203387,-84.7286,-70.817783,-121.15688,-88.072827,-78.768056,-93.299894,-97.026899,-87.6161,-86.398611,-106.65739,-85.37961,-83.670159,-85.57648,-83.902185,-117.123894,-83.718949,-87.323337,-74.44405,-86.294415,-86.370556,-89.06347,-77.475556,-80.359722,-72.010368,-120.010158,-95.249943,-76.553075,-76.462055,-79.920867,-97.477175,-97.473794,-82.456229,-76.43808,-89.809739,-88.8086,-82.691724,-110.9823,-82.6429,-74.676301,-80.868318,-80.61533,-82.793463,-82.424555,-80.198787,-85.181581,-74.695005,-80.342,-86.553035,-106.48982,-88.8283,-111.663056,-84.776429,-74.448736,-119.766212,-84.4052,-87.270967,-71.169235,-84.58825,-86.06085,-87.036236,-107.23056,-74.12525,-72.86884,-115.484144,-79.801111,-87.138246,-78.526194,-108.592334,-89.77183,-77.10468,-86.021389,-117.088649,-79.09197,-84.20077,-68.2609,-77.05922,-89.6797,-101.428056,-86.309694,-84.134412,-97.282088,-80.26567,-86.242649,-108.041111,-88.624943,-117.264088,-87.312883,-97.475083,-80.226438,-96.405726,-87.8499,-119.272606,-90.226488,-122.25556,-106.50126,-85.992451,-79.31881,-78.767867,-77.48925,-89.788459,-119.000974,-85.016821,-88.422045,-75.797317,-104.73744,-122.402194,-85.44428,-86.11,-86.395394,-94.42468,-97.431052,-119.79146,-89.357298,-76.6538,-76.811864,-70.713958,-87.901,-96.361196,-77.720244,-85.416608,-94.861289,-97.905931,-80.66272,-97.854129,-118.870496,-73.8589,-84.49761,-98.42879,-78.991692,-98.931973,-111.739999,-90.44917,-117.024484,-84.36625,-86.109408,-117.493304,-81.123519,-92.006318,-116.088333,-87.792235,-111.88431,-120.034203,-93.583983,-87.536667,-119.741966,-95.948435,-81.3785,-121.303144,-97.751503,-96.786419,-114.61444,-84.113808,-79.859167,-81.9239,-106.23586,-86.994,-119.055018,-120.428774,-95.882622,-85.852734,-88.499046,-97.679734,-97.484099,-81.3373,-85.656391,-106.548914,-89.1089,-77.042252,-74.255544,-118.809946,-104.485552,-76.111274,-85.870669,-87.718354,-85.766816,-77.30968,-119.291228,-83.47606,-111.76225,-97.03135,-79.012,-84.47445,-104.676944,-86.60325,-83.2377,-73.585128,-97.494309,-87.81,-77.3078,-76.939167,-86.152363,-76.387017,-120.681567,-83.946559,-80.572808,-116.929486,-72.334079,-85.0485,-118.683757,-111.852199,-119.717356,-106.7396,-76.203889,-83.0662,-103.37853,-97.303044,-94.035,-71.11397,-93.204411,-121.164457,-121.443324,-80.4554,-85.162194,-116.944222,-84.0539,-72.388056,-87.92,-111.83852,-88.548934,-117.396158,-117.41601,-120.953832,-119.71877,-111.855654,-94.265373,-78.919972,-117.85036,-86.148577,-120.04019,-106.5852,-119.807717,-80.143657,-105.370283,-107.62863,-117.62914,-72.630015,-93.20826,-118.783624,-97.436742,-87.8858,-81.575256,-117.22764,-72.07882,-106.768337,-120.148833,-86.99012,-90.148031,-117.92391,-76.617194,-116.0216,-119.262991,-80.503948,-105.2903,-94.377014,-81.242156,-112.06626,-70.023598,-72.71238,-70.785225,-119.875415,-86.907786,-117.67593,-92.09308,-71.423705,-83.000138,-119.247741,-111.805769,-119.64457,-98.03544,-118.330783,-84.1441,-104.817215,-94.57983,-87.50524,-73.297257,-81.422455,-83.28717,-91.652121,-71.878626,-118.5284,-105.586,-75.860051,-104.75308,-121.631916,-115.052942,-119.774174,-86.001629,-115.253333,-108.99495,-118.789424,-94.580931,-103.122917,-119.7661,-83.788502,-83.602077,-110.774357,-119.504569,-111.60925,-119.063542,-119.739606,-108.02611,-105.529994,-90.84927,-87.54535,-106.425827,-90.47606,-94.143521,-110.99644,-117.331433,-117.33098,-82.81555,-112.018863,-111.872222,-111.86507,-72.55327,-91.335868,-106.27767,-87.8093,-107.870219,-89.585869,-87.716213,-110.599472,-90.42388,-112.34184,-105.220238,-81.45879,-94.55594,-94.849,-120.379611,-112.160597,-87.675254,-117.92568,-111.884467,-117.27411,-82.0454,-121.100648,-115.56306,-119.840025,-106.584434,-68.22698,-118.53276,-111.660502,-111.987164,-107.652192,-120.04692,-89.959963,-107.8475,-104.262726,-73.103056,-80.169943,-114.060879,-111.652777,-112.353414,-115.263038,-119.956738,-90.32408,-89.69864,-97.275896,-101.941218,-111.73331,-113.305096,-120.631282,-87.796138,-80.5578,-111.67183,-111.987871,-110.182742,-110.009732,-122.7877,-111.72529,-110.098861,-108.619,-115.238282,-106.36501,-109.455315,-108.313835,-84.626423,-105.13948,-106.07968,-109.87076,-113.5586,-105.498931,-78.43471,-104.957193,-111.06352,-111.5436,-105.070358,-110.0551,-111.755334,-105.141122,-83.79562,-73.90312,-76.424386,-101.6649,-121.740367,-106.40971,-83.941606,-106.847222,-121.57646,-115.332728,-119.658339,-109.753,-104.778334,-103.17781,-115.357087,-108.761389,-109.3047,-113.562222,-83.497941,-108.473138,-119.243743,-109.906796,-117.397004,-117.27422,-104.901289,-109.561472,-104.191944,-105.29841,-118.131456,-103.48386,-81.249906,-109.788333,-116.178156,-107.616667,-105.177989,-71.303821,-104.569335,-107.549444,-83.074156,-118.852037,-83.609612,-120.033084,-115.4108,-104.4406,-106.683324,-82.7925,-115.362234,-109.38906,-112.036298,-109.353932,-109.688108,-108.49424,-109.89249,-111.042376,-111.1074,-106.698369,-117.14731,-107.484167,-120.23135,-110.737116,-112.01739,-113.1506,-114.846313,-118.82915,-110.800749,-119.016765,-109.560498,-110.40034,-116.21537,-121.003373,-82.264944,-83.235981,-120.821916,-105.188587,-106.50815,-106.9858,-111.285594,-114.21593,-105.983056,-107.904167,-116.85841,-119.7062,-117.083333,-117.285597,-112.463213,-108.49046,-121.618836,-111.855622,-114.907429,-116.768225,-109.82126,-116.54101,-108.720003,-115.676651,-105.54564,-116.847778,-112.18358,-118.147294,-116.365203,-109.788,-119.404826,-121.820362,-117.27235,-106.2399,-116.830074,-111.7987,-117.563939,-119.844591,-105.76398,-65.915482,-121.056591,-118.778995,-122.092766,-115.586128,-116.38893,-115.8206,-115.7767],[32983.1508379888,40667.2132352941,41050.1768707483,41795.0322580645,42353,43373.7889908257,43424.0895522388,43843.3333333333,43884.3741007194,44220.7132867133,44327.0222222222,45429.4207317073,45506.1255605381,45788.2244224422,45966.958490566,46141.8187311178,46392.6099706745,46434.0647058824,46726.6728971963,46795.4695121951,46878.2987804878,47586.2978723404,47641.1876923077,47808.2259136213,47880.4342857143,48098.0235294118,48143.2881355932,48306.5657894737,48336.0787878788,48393.3333333333,48618.3344051447,48808.6416666667,48882.2314540059,48885.5215946844,49366.7847222222,49395.2985507246,49554.1650793651,49636.0344827586,49722.5375722543,49743.445482866,49898.8132780083,49996.6622516556,50084.041322314,50345.8112094395,50390.2305475504,50470.8181818182,50471.9093484419,50530.9240121581,50591.1363636364,50697.6555891239,50721.4954407295,50759.5593220339,50778.6976744186,50821.8983050847,50901.9495798319,50926.173374613,50929.0029498525,51124.3277310924,51152.081871345,51185.3735632184,51249.2528089888,51257.8674351585,51292.308988764,51391.3665689149,51463.5702479339,51465.7119113573,51518.5014245014,51531.3669467787,51537.5694444444,51556.5850340136,51565.4901960784,51581.8558558559,51728.8757062147,51791.7422969188,51849.695473251,51856.7985347985,51933.610738255,52010.988372093,52046.1130742049,52054.0279329609,52114.7645259939,52138.8653295129,52203.8353658537,52210.7942028985,52344.6050420168,52404.8451882845,52407.0822510822,52426.2125,52436.357771261,52454.7190082645,52542.3123123123,52581.2549019608,52637.9887640449,52699.782729805,52736.7803468208,52741.1220930233,52805.4191780822,52926.8395061728,52935.1428571429,52946.1717791411,52947.1213872832,53000.5817174515,53047.0459770115,53051.2528735632,53051.7184466019,53051.9488817891,53127.9533527697,53153.720164609,53180.6279069767,53248.4367816092,53251.8624641834,53293.1253644315,53351.8222222222,53366.8700564972,53375.8757062147,53378.1327433628,53461.1737891738,53508.2994011976,53548.1751412429,53585.1930835735,53596.8167202572,53654.8979591837,53669.7797101449,53672.7670454545,53686.8870292887,53773.496969697,53819.1057401813,53832.1344537815,53853.2571428571,53857.0714285714,53876.3556851312,53897.4567901235,53914.4011142061,53944.9043478261,53956.2612244898,53977.6150627615,53993.5,54021.6589595376,54042.7089337176,54115.5575221239,54119.4150417827,54178.814159292,54242.0633484163,54248.298245614,54309.3204419889,54342.5589041096,54350.284057971,54364.7529411765,54374.9061488673,54379.0042553192,54382.1557377049,54424.6424242424,54491.237704918,54537.1778425656,54564.0821114369,54584.3082437276,54607.5802469136,54655.0551724138,54688.6068376068,54727.9508196721,54739.4972375691,54746.3910614525,54758.0738461538,54802.631147541,54818.3660130719,54821.9020408163,54837.0756302521,54887.9052132701,54903.5014005602,54929.1497005988,54930.938547486,54967.2113821138,54971.1444444444,54976.1829652997,54995.9680511182,55009.4577259475,55057.8857142857,55097.0060240964,55146.221574344,55148.9577464789,55166.2662889518,55172.4189944134,55225.7258566978,55232.9329608939,55246.7548638132,55264.9802816901,55355.4189944134,55401.9867549669,55405.4210526316,55512.8260869565,55545.7918552036,55563.9770114943,55577.5724137931,55719.9715099715,55746.3629893238,55782.3701657459,55792,55794.0639534884,55801.0170940171,55813.6261127596,55841.8833333333,55901.0198675497,55943.2602739726,55943.8072289157,55994.8513119534,55995.8270893372,56030.2766570605,56058.575,56073.1036414566,56074.7521367521,56129.479338843,56228.418079096,56249.0923694779,56263.4127906977,56268.1196581197,56270.7786885246,56277.9375,56287.6823529412,56312.5901639344,56410.3024691358,56446.502994012,56465.8491620112,56532.8265895954,56550.6846846847,56577.6112676056,56578.7857142857,56580.6204081633,56599.7836065574,56600.6526946108,56622.2170087977,56632.7058823529,56701.6023738872,56731.7729257642,56778.0857142857,56853.3764044944,56885.0934065934,56891.9349593496,56912.3333333333,56912.9491525424,56914.5892116183,56921.7004405286,56970.0802292264,56970.6858789625,56980.3137254902,56993.3583333333,57068.7136929461,57101.3238636364,57111.6765957447,57144,57163.3072625698,57185.3568281938,57226.9502262443,57227.8413597734,57240.8936781609,57277.899408284,57289.5074183976,57305.6541786743,57307.7994428969,57382.4365781711,57430.2492753623,57457.6239316239,57461.9879518072,57464.1034482759,57480.0677966102,57485.3295774648,57527.2407407407,57546.0529411765,57554.3,57626.1360946746,57632.7983193277,57645.4712643678,57654.1310541311,57668.2060085837,57680.649122807,57718.8421052632,57738.9070422535,57760.5459610028,57761.4285714286,57766.6902654867,57788.2049861496,57813.6878612717,57850.4228571429,57861.0654761905,57873.162601626,57900.1916666667,57907.2133891213,57967.3666666667,57970.2288135593,57975.4929577465,58011.7765363128,58043.3184357542,58051.6343490305,58058.8184615385,58067.838150289,58096.9178082192,58103.756097561,58135.2979351032,58158.5953757225,58179.8888888889,58195.075,58204.1551246537,58208.0842696629,58208.2195845697,58224.1596958175,58246.3438395415,58252.7288135593,58271.631147541,58282.2212765957,58326.9520958084,58363.589958159,58380.7302904564,58416.8112676056,58456.6315789474,58469.5950920245,58472.7654320988,58481.7744807122,58486.2960893855,58513.9159663866,58542.7829787234,58564.4754098361,58589.1689750693,58618.427672956,58628.2533936652,58671.621399177,58692.1724137931,58722.8849557522,58724.5395894428,58725.3431734317,58733.2897727273,58733.9004149378,58760.5371900826,58766.6944444444,58768.2743902439,58773.5889570552,58793.9423076923,58818.2848837209,58827.1225071225,58845.4514767932,58857.224137931,58878.5528455285,58885.5976676385,58912.5730337079,58952.1473087819,58957.4535211268,58964.9915966386,58980.3844011142,58986.5528455285,58997.3277310924,59004.2117647059,59009.7613636364,59035.095505618,59037.1206896552,59037.762295082,59092.3342939481,59116.7619047619,59117.1884057971,59129.9329608939,59130.5779036827,59152.6880466472,59174.582278481,59187.1460055096,59193.3109243697,59207.1942857143,59209.71875,59227.2485875706,59227.527696793,59245.787755102,59258.3183673469,59267.955922865,59274.3573487032,59281.7752161383,59294.7019230769,59326.6777777778,59344.3440233236,59371.3937677054,59379.426035503,59478.631147541,59491.476702509,59539.462295082,59542.7920792079,59560.364640884,59574.0405797101,59578.6875,59587.808,59588.5,59592.6934097421,59609.4540059347,59612.9173789174,59622.9482758621,59627.9648093842,59666.0692041522,59672.9361702128,59683.6050420168,59690.8962655602,59691.9416909621,59693.1878453039,59698.5620915033,59704.2865329513,59756.3185840708,59792.7112462006,59797.8929577465,59801.9833333333,59811.2541254125,59826.2540983607,59832.3553719008,59872.8820224719,59883.9755102041,59902.2973760933,59921.1300813008,59931.8246753247,59944.6550218341,59970.1412429378,60021.56,60023.0028818444,60032.9090909091,60046.4552845528,60086.9121813031,60157.0879120879,60185.7938718663,60186.9532163743,60195.9718309859,60214.0323624595,60235.9856321839,60242.8669201521,60245.1578947368,60246.5447154472,60249.1833333333,60263.7117647059,60323.0909090909,60343.6694214876,60382.3426966292,60426.4756097561,60429.7306122449,60465.2034883721,60478.4109589041,60484.3836734694,60497.3732193732,60497.9588477366,60513.9330543933,60520.9469387755,60526.3988764045,60532.2478873239,60543.0316742081,60543.1267605634,60574.4156626506,60673.8218390805,60686.8524590164,60716.01179941,60716.5561797753,60752.3703703704,60783.6910112359,60838.6363636364,60905.4310344828,60908.5619834711,60919.65,60930.5606694561,60941.5014164306,60943.4533762058,60947.1384615385,60947.145194274,60961.3390804598,60967.5659340659,60969.1686046512,60973.1437125748,60975.1008645533,60985.3795918367,60998.8385093168,61014.7988668555,61044,61054.1306122449,61077.4777070064,61078.5150214592,61095.6709219858,61106.3661971831,61115.1721311475,61135.5397260274,61142.7190082645,61144.4057971014,61230.5867768595,61249.0335195531,61275.6976744186,61300.9510086455,61309.1583333333,61310.5835694051,61319.3474320242,61342.2612244898,61342.7100591716,61375.039039039,61382.1475409836,61383.404494382,61394.9098360656,61417.7927170868,61428.0823045267,61444.2448979592,61470.6008230453,61486.0501392758,61550.2307692308,61556.7025495751,61556.9916666667,61571.6897959184,61576.5205479452,61612.3697478992,61633.8461538461,61676.2,61700.0877192982,61709.6091954023,61730.2822580645,61731.6625514403,61735.2601156069,61748.9310344828,61802.622406639,61826,61866.1762114537,61868.9781659389,61880.826446281,61886.0931899642,61889.0137741047,61890.4679245283,61898.7736389685,61960.5106382979,61971.3222222222,61993.1790633609,61996.2907488987,62017.0405904059,62018.7848837209,62039.9775910364,62057.1934156379,62073.1918367347,62095.525,62109.8592375367,62111.5027027027,62113.2716049383,62120.2542372881,62150.1685393258,62185.2154696133,62185.631147541,62204.2775510204,62220.1461988304,62225.9918367347,62330.8166666667,62378.5224719101,62383.7520661157,62402.5285285285,62435.0081300813,62455.9414225941,62496.5604395604,62527.1666666667,62529.7142857143,62578.5609756098,62585.0116959064,62615.9,62624.6666666667,62712.5723472669,62730.5064102564,62745.4522821577,62766.0578512397,62786.825,62794.7025495751,62797.0084507042,62867.0055555556,62880.9672131148,62899.0661157025,62928.5480225989,62941.82369146,62989.2680115274,63000,63023.9352941176,63032.2426778243,63077.6470588235,63165.7479674797,63183.3017241379,63184.0658436214,63184.4830508474,63209.8692810457,63219.7633802817,63230.7948717949,63271.4650205761,63283.6231884058,63300.948051948,63337.7469387755,63365.2333333333,63403.7994428969,63406.0511363636,63459.5168195719,63467.5184135977,63469.1092436975,63491.1219512195,63523.055393586,63536.6697674419,63539.7394957983,63543.5135135135,63544.6707317073,63563.8771929825,63568.1024096385,63581.7317073171,63708.4972067039,63716.1373390558,63718.73556231,63755.207977208,63783.6578171091,63805.3949579832,63819.0395136778,63829.0290456432,63841.7613168724,63867.5765199161,63870.209631728,63881.2219178082,63899.0807799443,63899.263803681,63899.5641791045,63901.9831460674,63911.1631799163,63913.4918032787,63915.6115702479,63925.7378917379,63934.2011173184,63938.3398328691,63945.2217573222,63949.8105849582,63982.3085714286,64038.9777777778,64041.8910505837,64059.3798219585,64060.4956268222,64074.0732394366,64118.7102040816,64162.08,64177.4084507042,64192.7853107345,64200.0278551532,64257.65,64296.3669467787,64343.4754098361,64356.8746518106,64359.0040650407,64374.9467787115,64417.1573033708,64427.2540983607,64428.8805031446,64440.006097561,64467.5180055402,64473.5694050991,64502.0169971671,64508.6863905325,64520.3137254902,64573.4893617021,64574.2343096234,64592.1498559078,64630.3616236162,64674.3697478992,64702.9421487603,64729.6617647059,64777.4907407407,64796.4418604651,64800.5590778098,64801.5764705882,64804.3856502242,64809.1588785047,64863.2057142857,64879.2011019284,64900.6666666667,64922.4101123596,64923.8683127572,64935.7206703911,64954.4303797468,64977.0530612245,64983.047318612,65010.4077669903,65020.3166666667,65044.2057613169,65049.3241758242,65050.3123287671,65056.1662049862,65189.1867219917,65240.9523809524,65247.5745856354,65253.4707520891,65271.1549295775,65271.3333333333,65278.4979591837,65281.4589665653,65283,65293.9232876712,65337.8079096045,65345.7355371901,65350.3346938776,65353.5182072829,65364.7088607595,65383.8583569405,65390.3102493075,65396.3428571429,65397.0416666667,65406.1219512195,65417.1168091168,65417.2564841499,65417.5346938776,65426.9907692308,65455.3551020408,65470.1333333333,65498.3673469388,65512.9593495935,65518.8846153846,65524.4049586777,65542.868852459,65545.9261363636,65549.9827586207,65581.787755102,65593.8666666667,65619.8766519824,65677.4356846473,65700.9387755102,65712.9469387755,65717.8418079096,65725.0833333333,65729.1731843575,65731.4471544715,65732.6970954357,65736,65762.2044198895,65767.5102040816,65770.0769230769,65774.8404255319,65775.6225352113,65785.498392283,65811.2099447514,65841.1358024691,65850.7983539095,65870.2100840336,65876.2258726899,65957.1522633745,65964.1487603306,65966.6445783133,66031.7981651376,66034.6363636364,66043.6131386861,66048.5882352941,66054.1610169491,66054.7591836735,66055.3095890411,66057.2817337461,66103.811965812,66125.3165266107,66135.3274336283,66149.3032786885,66170.6411764706,66174.893442623,66175.0946502057,66190.5423728814,66201.05,66315.2754491018,66324.9213483146,66340.9831460674,66353,66377.9209726444,66386.6946778711,66423.002739726,66424.3228699552,66437.4836065574,66440.7642276423,66450.2033898305,66541.3755274262,66552.2166666667,66553.9833795014,66601.4344262295,66619.6326530612,66711.3008130081,66712.1707317073,66718.955801105,66728.4326530612,66742.8571428571,66746.1140684411,66781.6585365854,66816.7786885246,66871.5847457627,66881.4222222222,66885.6797583081,66924.5403899721,66946.9915966386,66947.4895104895,66967.1721311475,66989.6405797101,67081.9673469388,67097.4943181818,67118.6723163842,67132.8617886179,67157.2282157676,67168.7723577236,67183.5690607735,67184.5387755102,67204.3844011142,67204.7020408163,67218.8258426966,67222.0687679083,67237.970845481,67259.0041493776,67305.4491525424,67363.602484472,67407.4552845528,67409.7724550898,67457.1056910569,67457.2711864407,67469.251396648,67503.3577235772,67551.0580645161,67557.5901639344,67567.9502762431,67595.0858725762,67596.8547486033,67608.0821917808,67637.4780058651,67646.9674796748,67672.3404255319,67677.4849785408,67685.1181556196,67693.3882352941,67696.7897727273,67740.4034582132,67763.041322314,67796.2857142857,67818.8505747126,67884.7008547009,67899.1814345991,67899.5447154471,67912.7901234568,67924.3452054794,67926.3127572016,67939.0165289256,67969.9175824176,67980.7479674797,67983.2931034483,67997.6593406593,68019.9674796748,68093.5983606557,68094.8926553672,68112.8126801153,68118.5327868852,68127.8563535912,68129.0204081633,68172.1111111111,68207.2427983539,68235.014084507,68237.243902439,68240.6554054054,68265.3860182371,68273.0348837209,68275.8012684989,68316.9461756374,68318.8418079096,68329.8847736625,68330.8664688427,68375.4277456647,68402.1959183673,68413.6916666667,68455.9090909091,68459.3086419753,68460.8991596639,68470.2049180328,68541.2923976608,68555.5944444444,68561.3974895398,68572.8524590164,68591.7283950617,68599.4146341463,68620.185915493,68631.7871148459,68674.2155172414,68735.9779005525,68813.7695473251,68814.7162790698,68834.9113924051,68845.7520661157,68881.3008130081,68888.132780083,68920.8797653959,68926.7877094972,68978.495412844,68988.2598870056,68996.3901098901,69001.1520467836,69030.6260162602,69054.4938271605,69054.5610859728,69098.9582172702,69157.5743440233,69161.4243070362,69179.3217391304,69216.6008230453,69231.0569105691,69233.1104651163,69252.3333333333,69306.4959349593,69365.0205479452,69367.375,69427.0909090909,69490.7845303867,69495.9905660377,69508.867768595,69521.8369905956,69540.8617886179,69545.6341463415,69556.6044776119,69556.8409090909,69571.2044817927,69578.0338983051,69581.0612244898,69586.4552845528,69601.0448979592,69666.4063492063,69715.1101694915,69717.7759103641,69725.5457063712,69726.5828571429,69748.8,69786.3510204082,69791.904494382,69829.0632183908,69833.1977715877,69864.5355648536,69899.5989010989,69924.5020920502,69945.5040650406,69946.6165413534,69951.8953168044,69963.8761061947,69985.1855955679,69986.868852459,69990.0689655172,70052.3434343434,70153.3091922006,70173.3352941177,70173.6081632653,70223.6509695291,70238.6956521739,70248.297752809,70270.2445414847,70306.4715447154,70399.9835390946,70425.3443526171,70437.8260869565,70478.4117647059,70491.9137931034,70509.7270194986,70512.3324099723,70572.8487394958,70585.1056910569,70620.461971831,70639.631147541,70652.081300813,70677.8337950138,70709.7016574586,70715.8487394958,70734.6684931507,70746.9826589595,70751.3801169591,70760.1377410468,70769.325203252,70772.8764044944,70781.9175824176,70782.6028169014,70824.590021692,70829.6080691643,70928.1422764228,70936.7670454545,70983.6232686981,71009.2990353698,71016.9105691057,71046.2967032967,71069.9510204082,71080.9158878505,71119.5914893617,71126.679558011,71149.7642276423,71169.2087912088,71210.4362606232,71219.547826087,71234.8271954674,71258.8222222222,71275.4775510204,71317.0581717451,71343.296398892,71359.6341463415,71370.3021978022,71373.0279329609,71408.3742690058,71433.9512195122,71439.6211699164,71451.2396694215,71473.7444444444,71483.3860465116,71510.0386740331,71546.3285302594,71562.2793296089,71588.9959183673,71597.621399177,71597.6703296703,71608.4056603773,71633.6308539945,71671.6997167139,71673.2098765432,71684.3423423423,71701.4333333333,71733.0622406639,71742.6481481481,71813.7402597403,71848.3774647887,71988.4065934066,72030.2717622081,72034.8130081301,72078.0941828255,72098.186440678,72130.8487084871,72219.8448753463,72229.9277777778,72243.5041322314,72258.9972451791,72280.5020576132,72283.5627906977,72320.8278688525,72340.9289617486,72346.870523416,72362.4550561798,72408.7068273092,72417.679558011,72419.487804878,72426.1828254847,72619.4448979592,72734.4894514768,72793.6759776536,72801.0975609756,72842.2040816326,72897.5609756098,72939.4450549451,72961.3608815427,72991.1586715867,73014.4734693878,73019.7419354839,73030.2045454545,73083.8622754491,73167.294117647,73199.2131147541,73272.3735632184,73299.8968481375,73301.9215686274,73392.3026584867,73579.9835164835,73617.5519125683,73671.9836734694,73746.9552238806,73760.3111111111,73785.182320442,73812.0991735537,73814.687150838,73818.9355742297,73932.5295774648,73959.402739726,74109.2786885246,74174.9711934156,74230.0936639118,74256.5613305613,74280.1277777778,74287.7692307692,74396.7811634349,74467.7,74531.3469387755,74641.1419354839,74728.8833922262,74735.9889807163,74752.8866995074,74786.3591836735,74801.6056338028,74809.9446640316,74893.3313953488,75034.2127659574,75064.9387755102,75071.1538461538,75159.864978903,75213.2887537994,75285.5542857143,75319.652892562,75376.9669421487,75406.4367346939,75429.1955922865,75435.9484240688,75450.1900826446,75457.2486187845,75536.4692082111,75642.9359331476,75686.9716088328,75768.864265928,75776.4848484848,75892.5393258427,75929.7307692308,75944.4179104478,76091.7127071823,76217.6978851964,76289.0809399478,76526.8605341246,76533.5376044568,76573.7851239669,76728.9392265193,76803.5524861878,76924.6790697674,76981.5540983606,76994.9398907104,77076,77102.7590027701,77109.5769230769,77185.456043956,77223.754601227,77227.1591836735,77236.9777777778,77344.098630137,77411.5512465374,77440.9944444444,77504.2105263158,77587.6086956522,77672.9971988795,77673.7434210526,77778.3581081081,77800.5082872928,77824.9150684932,77844.1052631579,77846.6741573034,78078.1538461538,78084.5942857143,78085.3994490358,78112.9230769231,78172.7342465753,78251.5934065934,78252.4786324786,78374.6765578635,78434.4493150685,78493.6978021978,78504.8066298342,78565.4630136986,78575.2947658402,78639.0304709141,78835.532967033,79003.0309859155,79017.2596685083,79132.6868131868,79159.2152588556,79207.860724234,79229.6134453781,79346.3209876543,79385.037037037,79389.5397260274,79506.2727272727,79512.602739726,79535.0714285714,79537.6558441558,79768.3085399449,79903.2658959538,79926.7507163324,79956.9808219178,79961.9323943662,80323.9890410959,80469.6923076923,80542.0989010989,80729.7967032967,80940.5545722714,80959.8469945355,81015.1342465753,81020.2521008403,81039.5780821918,81124.6590909091,81249.7517241379,81406.9433962264,81448.0109589041,81519.0092307692,81605.1726027397,81682.0443213296,81805.3223140496,81820.4552845528,81844.9534246575,81965.3650793651,82147.3150684932,82304.8486646884,82517.6932153392,82657.5258855586,82710.6666666667,82761.9917012448,82916.0386740331,82948.2762430939,82985.923566879,83416.1923076923,83546.5238095238,83687.1452054794,83721.1367521368,83754.7002967359,83816,83973.3036211699,84173.2657534247,84246.2684931507,84474.5056179775,84538.4547945205,84724.4958677686,84824.3736263736,84910.2307692308,84955.226519337,85380.202739726,85399.0591549296,85516.6904109589,85537.6712328767,85606,85681.6398891967,85819.7110481586,85844.9230769231,85856.0391061453,86122.7726027397,86536.0404624277,86691.4575342466,86706.0747663551,86744.0091743119,86755.5311004785,87021.8042813456,87068.2950819672,87327.2219178082,87827.3988764045,87906.8033707865,87998.8296703297,88081.591160221,88120.8472222222,88177.298630137,88188.898630137,88309.8082191781,88390.0621468927,88460.3212121212,88785.4515235457,88857.1123287671,89376.3123287671,89911.402173913,90191.8131868132,90724.1970149254,91112.3626373626,91135.4608695652,91250.8771929825,91251.9693165969,91479.0764872521,92474.1917808219,93596.0550964187,93793.1102661597,93807.901369863,94177.2375,95079.6153846154,95455.2256267409,97773.6220930233,99135.3663911846,99443.6219178082,99470.4444444444,99935.0049751244,100000.703225806,100728,101120.734246575,102603.125581395,103474.358208955,103736.61038961,103904.451790634,104865.072580645,105734.931034483],null,null,{"interactive":true,"className":"","stroke":false,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":["#FFFFCC","#FFF1A9","#FFF8BC","#FFEDA1","#FFF5B3","#FFE28A","#FFF1AA","#FFF2AC","#FFF1AB","#FFF4B2","#FFE38B","#FFF2AD","#FFDE82","#FFF0A7","#FFE997","#FFE289","#FFEA9A","#FFE58F","#FFEDA0","#FFE38A","#FFE998","#FEDD7E","#FFE58F","#FFE896","#FFE590","#FFE998","#FEDB7B","#FED773","#FFE289","#FED673","#FFEB9B","#FEDD7E","#FFEFA5","#FFEDA0","#FFEC9E","#FFEA99","#FFE084","#FFEC9F","#FFE187","#FFE692","#FED572","#FFE58F","#FFE288","#FFE48E","#FFEA9B","#FFEC9F","#FEDD7F","#FFE794","#FEDC7B","#FFE186","#FFE590","#FFDF84","#FFE085","#FFE187","#FFE289","#FEDC7D","#FFE084","#FED26F","#FFDF82","#FEDC7C","#FFEA99","#FFE187","#FFEA9B","#FEDD7F","#FED774","#FFDF83","#FFE085","#FEDA78","#FFE997","#FFCF6B","#FED875","#FFE38A","#FFE085","#FFE084","#FED976","#FECF6B","#FFCF6B","#FEDA77","#FFE289","#FFDF84","#FFE084","#FFE48E","#FFE38C","#FFE188","#FEDC7C","#FED773","#FED875","#FEDD7F","#FFE38A","#FED471","#FFDE82","#FEDA79","#FFE38A","#FFE085","#FFDE81","#FFE38A","#FFE48C","#FED774","#FFE38B","#FFE38B","#FFDF83","#FFE692","#FFDF82","#FFE084","#FFE085","#FFE48D","#FFE085","#FEDB7B","#FFE58F","#FFE38C","#FEDB7A","#FEDE80","#FFDE81","#FFDF83","#FFE590","#FEDA78","#FFDF83","#FFDF82","#FEDC7C","#FED471","#FEDB7A","#FED471","#FFE084","#FEDD7F","#FED36F","#FEDB7B","#FEDE80","#FFEC9E","#FEB54F","#FFE38B","#FFE085","#FED976","#FEDD7E","#FFE188","#FED977","#FEDC7D","#FFDE80","#FFE590","#FFE28A","#FFDF83","#FFE288","#FFDE81","#FEDA77","#FFCE6A","#FFE38B","#FFE58F","#FED774","#FFE692","#FED26F","#FEDB7B","#FED975","#FFDF82","#FED977","#FEDD7E","#FFE085","#FFDF82","#FFE084","#FFE085","#FED370","#FED875","#FFE187","#FFE48E","#FFDE82","#FED774","#FED571","#FEDD7E","#FFC965","#FEDC7D","#FFE58F","#FFDE82","#FEDC7B","#FEDE80","#FFE692","#FFE084","#FFE692","#FEDB7A","#FFDE81","#FEDB7A","#FEDB7A","#FED773","#FFDE80","#FFE691","#FEDB7B","#FFE084","#FEDB7B","#FFE793","#FFDF84","#FFE086","#FED673","#FFC965","#FED673","#FFE186","#FFE187","#FFE794","#FEDA79","#FEDB7B","#FFE48D","#FEDA78","#FEDD7F","#FED874","#FEDD7F","#FED673","#FEDD7E","#FFE085","#FEDB7B","#FFE38B","#FEDD7F","#FFDE80","#FFE288","#FFE48C","#FED26E","#FEDD7E","#FFCF6B","#FEDB7A","#FFE794","#FED16D","#FFDF83","#FED976","#FED470","#FED26E","#FED672","#FEDB7B","#FED774","#FED26E","#FFDF82","#FFDF83","#FECF6C","#FEDB7A","#FFDE82","#FEDC7C","#FFEA9A","#FEDC7C","#FED36F","#FED977","#FFE086","#FEDA78","#FEDC7C","#FED16D","#FED572","#FFC863","#FFE692","#FEDA79","#FFE086","#FFC662","#FFE289","#FED26E","#FFE086","#FED26E","#FFC965","#FEDE80","#FFE38B","#FEDB7B","#FFDF84","#FFE085","#FEAD4A","#FEDC7D","#FFE48D","#FEDA79","#FEDA77","#FEDC7C","#FED975","#FEDB7B","#FFCB67","#FED875","#FFE186","#FEDA78","#FEDA78","#FED875","#FEDB7A","#FED16D","#FFDF83","#FEDD7F","#FFCB67","#FED875","#FEDB7B","#FFE289","#FED977","#FED16D","#FFE288","#FED370","#FFCC69","#FEDB7A","#FED774","#FED16D","#FED370","#FFCA66","#FED16E","#FFE897","#FFDF83","#FFDF83","#FFE084","#FFE289","#FFE186","#FEDC7D","#FEDB7B","#FEDC7D","#FEDD7E","#FEDC7C","#FD873A","#FFDE81","#FFE085","#FFE187","#FEDB7A","#FFDF83","#FEDA79","#FEDB7A","#FED875","#FEBB56","#FFC561","#FED673","#FED16D","#FEDC7C","#FFC15C","#FFCA66","#FFCD69","#FFC35E","#FED571","#FEDC7D","#FFCA66","#FFE085","#FEDB79","#FFCB67","#FED26F","#FED774","#FFE48C","#FEDC7D","#FED875","#FEDC7D","#FED976","#FED875","#FEDC7C","#FFDF83","#FEAB49","#FED16E","#FFDF83","#FFE086","#FEDC7C","#FFC35E","#FED875","#FFC45F","#FEDB7A","#FED673","#FEDB7A","#FEDA78","#FEDD7E","#FEDB7B","#FED36F","#FFE086","#FEDC7C","#FFDF83","#FEDA78","#FED673","#FED06C","#FEDB7A","#FED774","#FED976","#FEDC7D","#FEDC7D","#FECF6C","#FEDD7E","#FFDE82","#FEDC7D","#FED16E","#FFE086","#FEDB79","#FFCB67","#FFCD69","#FEDC7C","#FFE692","#FEDE80","#FFE288","#FFC460","#FED673","#FED470","#FEDC7D","#FED874","#FECF6B","#FED16D","#FFE086","#FFCC67","#FEDA78","#FEDB7A","#FFC964","#FFCB67","#FED26E","#FED470","#FEDA79","#FED976","#FED672","#FEDD7E","#FED26E","#FED06D","#FED673","#FFE38B","#FFC05B","#FFC964","#FFCA66","#FEDB7A","#FFBD58","#FFE48C","#FEDC7C","#FFE28A","#FEDC7D","#FED471","#FED572","#FFCE6A","#FED572","#FED673","#FED16D","#FEDD7E","#FFC25D","#FED874","#FFE38B","#FFDE82","#FEDB7B","#FFC460","#FED26F","#FEDC7C","#FED875","#FED06D","#FED571","#FFC864","#FFDF82","#FEDB7B","#FED16E","#FFCB67","#FEDB7B","#FED36F","#FEDC7D","#FED976","#FEDD7F","#FFBF5A","#FED875","#FFDE81","#FED875","#FFCD69","#FEDD7F","#FFCB67","#FED672","#FFCA66","#FEDC7C","#FED875","#FEDB7B","#FED572","#FED26F","#FED977","#FED16E","#FEDB7A","#FFDF83","#FFC763","#FEDA77","#FED977","#FD7333","#FFE085","#FFE289","#FFCC68","#FEDB7B","#FECF6B","#FED16D","#FEDA77","#FFE590","#FFDF82","#FEDC7C","#FECF6B","#FED572","#FED16E","#FED470","#FED26F","#FED773","#FEDA78","#FFC661","#FED572","#FFCE6A","#FED16D","#FFCD69","#FFCC68","#FFDE81","#FFCB67","#FFC661","#FFDF84","#FED976","#FED26E","#FFDE81","#FEDC7D","#FFC25D","#FED36F","#FED672","#FED572","#FED370","#FFDE80","#FECF6C","#FED572","#FEDA78","#FFC561","#FED774","#FFDE81","#FEDA79","#FED471","#FFC25D","#FED875","#FEDD7F","#FED976","#FFCA66","#FED572","#FED976","#FED370","#FFC05B","#FED470","#FFE691","#FFCA66","#FFCD69","#FED06C","#FEDA79","#FEDB7A","#FEAD4A","#FED26E","#FED977","#FFC864","#FEDA77","#FEDA78","#FFE28A","#FFDE80","#FED572","#FFCD69","#FFCC68","#FED975","#FED774","#FED673","#FFCD69","#FFC662","#FFCA66","#FEDB7B","#FFCB67","#FED673","#FFC05B","#FED673","#FFC964","#FED774","#FFCB67","#FD8138","#FFDE80","#FEDD7F","#FFBE59","#FFE186","#FFCB67","#FEDB7A","#FEB953","#FED06D","#FEDB7A","#FED26F","#FFC460","#FEDA79","#FEAD4A","#FFCF6B","#FED572","#FEDA79","#FFC661","#FEDA77","#FED774","#FFE187","#FED471","#FFCB67","#FEAF4A","#FEDC7C","#FEDB7A","#FFEA99","#FEB751","#FED06D","#FECF6C","#FED370","#FFC864","#FED06D","#FED673","#FEAD4A","#FED672","#FED471","#FED976","#FFC964","#FEBA54","#FED976","#FED572","#FED672","#FED774","#FED774","#FED06D","#FFCF6B","#FFCA66","#FEDD7F","#FFDF83","#FEB24C","#FFCE6A","#FED571","#FED36F","#FFC661","#FED976","#FFE188","#FFC05B","#FED370","#FEDC7C","#FFC662","#FED370","#FEDB7B","#FFC15C","#FFE085","#FFC662","#FEB04B","#FEDB7B","#FEBD57","#FFC561","#FEDD7E","#FED875","#FFCE6A","#FED977","#FECF6B","#FFDF83","#FFDF82","#FFC35F","#FFC25D","#FFCB67","#FEDD7F","#FED470","#FEDA79","#FFDF82","#FFE38C","#FEA446","#FEDA77","#FEB751","#FED26F","#FE9C42","#FEDC7C","#FFC662","#FFDF82","#FEB853","#FEDB7A","#FFC25D","#FED976","#FED572","#FEBB56","#FE9D42","#FED36F","#FED976","#FED774","#FEDA78","#FEB853","#FED572","#FED06C","#FED16D","#FD913E","#FED06D","#FFC661","#FFC460","#FED875","#FEDD7F","#FEB34D","#FED976","#FD953F","#FFC15C","#FFC763","#FEAB49","#FED976","#FEB650","#FFC863","#FFCD69","#FED874","#FEDD7E","#FEB751","#FED370","#FFE187","#FEDA78","#FFC661","#FED773","#FFDE80","#FFDE81","#FFBF5A","#FEDA79","#FEDA79","#FEDA78","#FFBD58","#FED06D","#FFCE6A","#FEDA78","#FEB24C","#FFC45F","#FEAE4A","#FED36F","#FFC15C","#FEDE80","#FED16D","#FD8E3C","#FED370","#FFCD69","#FFCB67","#FFC965","#FFE085","#FEB954","#FFC561","#FEDD7E","#FFCD69","#FED976","#FFBF5A","#FED16E","#FEB751","#FEB954","#FEB651","#FE9841","#FFBE59","#FEB651","#FEAE4A","#FFCA66","#FFC763","#FFCB67","#FFBE59","#FED16D","#FEB651","#FED976","#FFCE6A","#FED16D","#FEDC7D","#FED16D","#FECF6B","#FEDB7A","#FED06C","#FFCC68","#FED976","#FFCA66","#FFCA66","#FEBC57","#FFBF5A","#FED774","#FFC763","#FED976","#FFCC69","#FED977","#FFC560","#FED571","#FED875","#FED471","#FEB953","#FEB54F","#FEA747","#FFC560","#FED875","#FEDD7E","#FFCD69","#FE9D43","#FFCD69","#FFCD69","#FFC560","#FFC15C","#FED16E","#FFCE6A","#FEDA78","#FFC864","#FED673","#FEDA79","#FFC05B","#FEB44E","#FFC15C","#FFC864","#FFCE6A","#FFCC68","#FFCC68","#FEBB56","#FFCE6A","#FFC965","#FFC662","#FED36F","#FEB853","#FFC762","#FED470","#FFC15C","#FED26F","#FFCA66","#FFC460","#FFE085","#FED572","#FEDA79","#FD8B3B","#FECF6B","#FFC662","#FED875","#FED16D","#FFC25E","#FFC45F","#FFC864","#FED36F","#FFC662","#FFDE82","#FFCE6A","#FEB44E","#FED673","#FED672","#FED26E","#FEDC7C","#FFC25D","#FEBC56","#FED774","#FFC763","#FED977","#FEBA55","#FFC762","#FED26F","#FFC965","#FEAD4A","#FFCB67","#FED673","#FE9D43","#FED26F","#FED572","#FED673","#FFCB67","#FFBF5A","#FFBF5B","#FEBC57","#FFC35E","#FFDE80","#FE9841","#FEB853","#FED16D","#FED875","#FFC965","#FED976","#FFC965","#FFC25D","#FEAE4A","#FFC965","#FEB651","#FEDD7F","#FFC05B","#FED471","#FEDB7A","#FFC05C","#FEBC57","#FFC05B","#FED774","#FED572","#FED572","#FFBF5A","#FED26E","#FFC45F","#FFC561","#FFBD58","#FFC965","#FED875","#FD7D37","#FEB54F","#FEB24C","#FEB54F","#FFC25D","#FED16D","#FEDA77","#FFC05B","#FEB54F","#FC532B","#FFC460","#FED370","#FEBA55","#FEAA49","#FEB34E","#FFC561","#FFC35F","#FFC965","#FFCC68","#FEBD58","#FFC965","#FFCA66","#FEDD80","#FEB650","#FED26E","#FFC05C","#FECF6B","#FFC15C","#FFC762","#FED06C","#FED370","#FFC15C","#FED774","#FEB14B","#FEDC7D","#FFC965","#FFC863","#FFC25D","#FFC45F","#FEB953","#FEB34D","#FEA647","#FEB954","#FFCE6A","#EC3121","#FEB852","#FECF6B","#FEB04B","#FFCA66","#FE9A42","#FD873A","#FED16E","#FFC05B","#FD8138","#FFC25E","#FFCD69","#FEA245","#FFC561","#FFC25D","#FEB650","#FFC25E","#FFC460","#FFC45F","#FFCD69","#FED16D","#FD7B36","#FEDA78","#FFCC68","#FFC15D","#FFCC68","#FFC35E","#FFC15C","#FED673","#FFC662","#FEAE4A","#FFCE6A","#FEBC57","#FED26F","#FE9D43","#FEDC7D","#FED471","#FFBE59","#FEBB56","#FFC35E","#FED572","#FC572C","#FFC35E","#FEB24C","#FFCA66","#FFCB67","#FFC15C","#FED26E","#FFC460","#FEDB7B","#FEB651","#FFC35E","#FFC662","#FED774","#FEDA78","#FFCA66","#FFC662","#FE9C42","#FFC05B","#FFC25D","#FEB34D","#FED572","#FED572","#FD903D","#FFC35E","#FD6E32","#FEAF4A","#FFBF5A","#FED976","#FED774","#FFC560","#FFCC68","#FED06D","#FFC763","#FEA647","#FEBB55","#FED571","#FEBC57","#FEA948","#FFC05B","#FFC965","#FEBB56","#FEA145","#FEB54F","#FFBE59","#E1191D","#FEAB49","#FEB44E","#FD9640","#FFC15C","#FFCD6A","#F74627","#FEBB55","#FEAF4A","#FEB34D","#FEB24C","#FEB34D","#FED06C","#FEB14B","#D31021","#FEBA54","#FEDA79","#FEAF4A","#FEB650","#FEB54F","#FFC35E","#EF3722","#FFBE59","#FEB04B","#FFC762","#FEBC57","#FEBA54","#F64527","#FEBA55","#FED976","#FE9F44","#FFCE6A","#FFCE6B","#FEBC56","#FFBF5A","#FD7835","#FED16D","#FFC05B","#FED36F","#FD6F32","#FEB852","#FD953F","#FFCC68","#FFC965","#FEA948","#FFBD58","#FEA145","#FD6D32","#FFBE59","#FEB651","#FEB954","#FEAC49","#FFC25D","#FFC965","#FED26E","#FEB44E","#FEBB56","#FFC864","#FED673","#EC3021","#FFBE59","#FEB751","#FFC25D","#FEDA77","#FEAC49","#F94828","#FEBA54","#FEA245","#FFC965","#F44025","#FEB24C","#FEB04B","#FEB650","#FEBB55","#FEB54F","#FEA948","#F54326","#FE9D43","#EB2E20","#FEBB55","#FFBE59","#FFBF5A","#FFC05B","#FEAB49","#FEB34D","#FEB44E","#FED370","#FEB650","#FE9941","#FA4A29","#FEB852","#FEB853","#FD8F3D","#FD7835","#FEA948","#FFC05B","#FFBF5A","#FEAA48","#FEAC49","#FEB852","#FEB24C","#FFCC68","#FEB954","#FE9740","#FEA345","#FFBE59","#FEBB55","#FFC35E","#FD8F3D","#FEAD4A","#FEAA49","#FEAC49","#FE9A41","#AC0026","#FFCC68","#FD9640","#FD903D","#FEAC49","#FEA245","#FFBF5A","#F13A23","#FEA747","#FFC460","#FEA446","#FFC864","#FE9C42","#FFC561","#FE9A41","#FEA647","#FEAE4A","#FEAB49","#FEAE4A","#FEA646","#FE9A41","#FFC15D","#FEB04B","#FEB954","#FEA345","#FFC35E","#FE9740","#FEB650","#FFCC68","#FEA847","#FFCC69","#FEAC49","#FE9941","#FEB14C","#FEAB49","#FEA144","#FEA948","#FEB752","#FEBB55","#FE9840","#FEBA55","#FFC561","#FEBB56","#FFC35E","#FE9C42","#FEB24C","#FEB04B","#FEB24C","#FFC25D","#FFCC68","#FE9A41","#FEAC49","#FE9A42","#FD8D3C","#FEB852","#FD873A","#FEA044","#FFC560","#FFC15C","#FEA044","#FEB651","#FFC560","#FEAA48","#FFC35E","#FEAF4B","#FFBD58","#FEA245","#FD6630","#FEB44F","#FEB14C","#FFC561","#FEB04B","#FEB34D","#FEAB49","#FFC45F","#FFBE59","#FE9E43","#FD8B3B","#FFBD58","#FEA345","#FEB04B","#FEA948","#FEAD4A","#FFC45F","#FEAE4A","#FD7033","#FFC05B","#FEB04B","#FEB14B","#FD5C2D","#FEB853","#FD943F","#FEB853","#FE9E43","#FEBA54","#FEBC56","#F23D24","#FFBD58","#FEB04B","#FEAC49","#FEAA48","#FD7A36","#FEBB56","#FE9D43","#FEAB49","#FD953F","#FEB24C","#FD9640","#FEB550","#FEAD4A","#FEB852","#FEA446","#FEA647","#AC0026","#FEAF4A","#FEAD4A","#FEA044","#FE9D43","#FEAE4A","#FEB14C","#F44025","#FEA345","#F74627","#FEA848","#FEB852","#F84828","#FC4E2A","#FEB24C","#FEB04B","#FD903D","#FD893B","#FE9E43","#FEAA48","#FD933F","#FEB24C","#FEAC49","#FEA345","#DD171E","#FE9F43","#FA4B29","#EF3723","#FE9941","#FEAE4A","#FE9740","#FD7634","#FD7B36","#FB4C29","#FEAF4B","#F44025","#FEAE4A","#FD903D","#FEA044","#FEA647","#FEAA48","#FD5F2E","#FD933E","#FEA747","#FA4B29","#FD933F","#A80026","#FE9941","#D21021","#FD8339","#E0181D","#FD602E","#FD8D3C","#800026","#EE3522","#D51220","#FC4F2A","#FD7233","#F03823","#FC502A","#FC542B"],"fillOpacity":0.6},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]},{"method":"addLegend","args":[{"colors":["#FFFFCC , #FFEA99 14.5692037176589%, #FFCB67 29.5570627145608%, #FE9D43 44.5449217114628%, #FD5F2E 59.5327807083647%, #E41D1D 74.5206397052667%, #B30026 89.5084987021687%, #800026 "],"labels":["30 - 40","40 - 50","50 - 60","60 - 70","70 - 80"],"na_color":null,"na_label":"NA","opacity":1,"position":"bottomright","type":"numeric","title":"Avg. Daily Air Quality Index","extra":{"p_1":0.145692037176589,"p_n":0.895084987021686},"layerId":null,"className":"info legend","group":null}]}],"limits":{"lat":[18.177939,48.95074],"lng":[-124.62491,-65.915482]}},"evals":[],"jsHooks":[]}</script><!--/html_preserve-->
It looks like AQI is the worst in California and still not so great in Arizona, Colorado, and Wyoming. Let's create a scatter plot with a linear model to look at the correlation between both AQI with Ozone and AQI with Nitrous Dioxide.


```r
library(gridExtra)

p1 <- ggplot(data = daily_mean_no2_df, 
             mapping = aes(x = DailyMeanPPB, y = DailyMeanAQI)) +
  geom_point() +
  geom_smooth(method = 'lm') + 
  scale_y_continuous(limits = c(0, 80)) +
  xlab('Nitrous Dioxide (ppb)') +
  ylab('Air Quality Index') +
  ggtitle('Relationship between NO2 and AQI in 2017')

p2 <- ggplot(data = daily_mean_o3_df, 
             mapping = aes(x = DailyMeanPPB, y = DailyMeanAQI)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  scale_y_continuous(limits = c(0, 80)) +
  xlab('Ozone (ppb)') +
  ylab('Air Quality Index') +
  ggtitle('Relationship between Ozone and AQI in 2017')

 grid.arrange(p1, p2, nrow = 1)
```

![](nitrous_dioxide_in_us_analysis_files/figure-html/unnamed-chunk-17-1.png)<!-- -->

There is a positive relationship for both variables with AQI. NO$_2$ seems to be a stronger predictor of high AQI than O$_3$.
